.github/workflows/golangci-lint.yml
Makefile
api/v1beta1/conversion.go
controllers/hcloudmachine_controller.go
controllers/hetznercluster_controller.go
hack/tools/tools.go
pkg/csr/csr.go
pkg/packer/packer.go
pkg/scope/cluster.go
pkg/scope/hcloud_client.go
pkg/scope/machine.go
pkg/services/loadbalancer/loadbalancer.go
pkg/services/network/network.go
pkg/services/placementgroup/placementgroup.go
pkg/services/region/region.go
pkg/services/server/server.go
pkg/utils/utils.go

/kind cleanup
This PR is a clean-up fixing all issues shown by golangci-lint.
```release-note
NONE
```

:seedling: Implementing linting guidelines

---

.github/pull_request_template.md
CONTRIBUTING.md

/kind other
Improving guidelines for contribution.

:book: Improving contribution guidelines and pull request template

---

.golangci.yaml
api/v1beta1/hcloudmachine_webhook.go
api/v1beta1/hcloudmachinetemplate_webhook.go
api/v1beta1/hetznercluster_webhook.go
api/v1beta1/hetznerclustertemplate_webhook.go
controllers/csr_controller.go
controllers/hcloudmachine_controller.go
controllers/hetznercluster_controller.go
pkg/services/region/region.go

/kind cleanup 
Adding golint to golint-ci and adding comments to several exported functions to follow the guidelines.

:seedling: Adding comments to exported functions

---

Makefile
Tiltfile

:seedling: Fixing make & tiltfile

---

.github/workflows/golangci-lint.yml
.github/workflows/shellcheck.yml
.github/workflows/starlark-lint.yml
Makefile

/kind other
Adds shellcheck and Starlark linting. And reconfigures linters behavior.

:seedling: Adding shellcheck and starlark lint

---

code-of-conduct.md

:seedling: Adding code-of-conduct

---

docs/developers/development.md

:book: Updating development guidelines to image usage.

---

pkg/services/server/server.go

Hcloud servers sometimes get stuck when shutting down. This PR introduces a mechanism using conditions checking if the shutdown has been done more than 30 sec earlier. If so, then just delete the server immediately. 
Fixes https://github.com/cluster-api-provider-hcloud/cluster-api-provider-hcloud/issues/101
- [ x] squashed commits

:bug: Using conditions to avoid servers not shutting down

---

Makefile
Tiltfile
api/v1beta1/hetznercluster_types.go
api/v1beta1/zz_generated.deepcopy.go
pkg/services/hcloud/loadbalancer/loadbalancer.go
pkg/services/hcloud/network/network.go

:bug: Fixing issues when using no private network

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CONTRIBUTING.md

:book: Fixing typo and contribution guidelines

---

Makefile
hack/ensure-clusterctl.sh
hack/ensure-go.sh
hack/ensure-tilt.sh

Updates dependencies in hack directory and Makefile

:seedling: Updates dependencies and Makefile

---

templates/node-image/test-image/scripts/cleanup.sh
templates/node-image/test-image/scripts/configure_base.sh
templates/node-image/test-image/scripts/configure_cri.sh
templates/node-image/test-image/scripts/configure_kubernetes.sh

/kind feature           New functionality.
Updates the node image to k8s v1.22 and clean-up the scripts.

:sparkles: Updating os-image to k8s v1.22 and cleanup

---

templates/cluster-template-packer-hcloud-network.yaml
templates/cluster-template-packer-talos.yaml
templates/cluster-template-packer.yaml
templates/cluster-template.yaml

/kind feature           New functionality.
Adds cloud-init based OS provisioning for easier testing with the new quickstart guide.

:sparkles: refactor of cluster-templates and adds cloud-init based OS provisioning

---

.github/workflows/golangci-lint.yml
.golangci.yaml

Fixes issue with external tilt-modules directory.

:bug: Fixes issue with external tilt-modules directory.

---

controllers/csr_controller.go

Updates the csr controller from deprecated v1beta1 to v1, so that it's compatible with k8s v1.22

:seedling: Updates the csr controller from v1beta1 to v1.

---

go.mod
go.sum

/kind cleanup           Adding tests, refactoring, fixing old bugs.
Cleanup of go.mod and go.sum

:seedling: cleanup; go mod tidy

---

README.md

Fixes broken link in the readme

:book: Fixes broken link in the Readme.

---

config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml
config/rbac/role.yaml
controllers/csr_controller.go
controllers/hetznercluster_controller.go
pkg/services/hcloud/loadbalancer/loadbalancer.go
pkg/services/hcloud/server/server.go

Fixes multiple issues with the csr controller if the kubelet flag rotate-server-certificate is true.

:bug: Fixes CSR Controller

---

README.md
docs/README.md
docs/topics/csr-controller.md
docs/topics/quickstart.md

Adds documentation what the csr controller is doing and how it could be enabled. Fixes also minor things in the Readme and quickstart and adds how to move resources from the management cluster to the target cluster.

:book: Adding documentation about csr

---

pkg/services/hcloud/placementgroup/placementgroup.go

:bug: Fixes error handling on placementgroup

---

Tiltfile
hack/ensure-tilt.sh

Updating tilt - adding new buttons and secret patch for clusterctl move

:seedling: Updating tilt - adding new buttons and secret patch for clusterctl move

---

.github/workflows/release.yml
.golangci.yaml
Dockerfile
docs/developers/development.md
go.mod
hack/ensure-go.sh
hack/tools/go.mod

/kind other
Updating to latest Go version.

:seedling: Updating Go version to 1.17

---

.golangci.yaml
Makefile
hack/ensure-go.sh

Removes deprecated linter, alignes that we now use go1.17.6. And cleans up the Makefile and fixes the make verify command.

:seedling: Removing deprecated linter; aligning to go1.17.6; cleanup makefile

---

README.md
docs/developers/updating-kubernetes-version.md
docs/topics/quickstart.md

Fixing the quickstart guide and adds information in the readme about the csr controller.
Also adds docs where to update the kubernetes version in the files.

:book: Fixing quickstart guide; adding docs where to update k8s version in files.

---

api/v1beta1/hcloudmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml
templates/cluster-template-hcloud-network.yaml
templates/cluster-template-packer-hcloud-network.yaml
templates/cluster-template-packer-talos.yaml
templates/cluster-template-packer.yaml
templates/cluster-template.yaml

/kind api-change        Adds, removes, or changes an API
Changing in HCloudMachineTemplate placementGroup to placementGroupName to align with naming convention

:warning: Changing in HCloudMachineTemplate placementGroup to placementGroupName to align with naming convention

---

api/v1beta1/hcloudmachine_webhook.go
api/v1beta1/hcloudmachinetemplate_webhook.go
api/v1beta1/hetznercluster_webhook.go
api/v1beta1/hetznerclustertemplate_webhook.go
controllers/hetznercluster_controller.go
main.go
pkg/scope/cluster.go
pkg/services/hcloud/server/server.go
pkg/utils/utils.go

Fixes some minor thing introduced by PR #50

:bug: Fixing some minor things after the cleanup

---

Makefile
Tiltfile
hack/ensure-tilt.sh

This refactors the Makefile for creating a target cluster, and also adds new targets for creating a cluster and for installing cni and ccm helpful when not using tilt for the target cluster. Also adds the debug log level as default level when using tilt. 
Updates tilt to the latest version.

:seedling: Refactoring of makefile and adding debug level in tiltfile - updating tilt as well

---

controllers/hetznercluster_controller.go
main.go

This is especially useful in the case where the main manager loses
leader election, as in this case the binary will end without a context
being canceled due to SIGTERM or SIGINT. Now we wait for target cluster
managers to shut down before we finish.
Removing leader election from target cluster managers as it doesn't
work well to have multiple managers in one binary performing different
leader elections.
**TODOs**:

:bug: Adding a wait group to allow gracefull shutdown of target clusters

---

Tiltfile
api/v1beta1/hetznercluster_webhook.go
config/manager/manager.yaml
main.go
templates/cluster-template-hcloud-network.yaml
templates/cluster-template-packer-hcloud-network.yaml
templates/cluster-template-packer-talos.yaml
templates/cluster-template-packer.yaml
templates/cluster-template.yaml

Update cluster-templates and defaults in Tiltfile and main.go

:seedling: Update cluster-templates and defaults in Tiltfile and main.go

---

Makefile
Tiltfile
templates/cluster-template-hcloud-network.yaml
templates/cluster-template.yaml

updated to k8s-1.23 and dependencies

:seedling: updates cluster-template to use Kubernetes v1.23.3 and updates related deps

---

README.md
docs/developers/development.md
docs/topics/quickstart.md

Updating version matrix and guides

:book: Updating version matrix and guides

---

hack/ensure-clusterctl.sh
hack/ensure-ctlptl.sh
hack/ensure-hcloud.sh
hack/ensure-helm.sh
hack/ensure-helmfile.sh
hack/ensure-kind.sh
hack/ensure-kubectl.sh
hack/ensure-packer.sh
hack/ensure-tilt.sh
hack/kind-dev.sh
hack/verify-shellcheck.sh

There are a lot of outdated deps, which are now updated. Please use make install-dev-prerequisites to upgrade.

:seedling: updating scripts to newest version

---

.github/linters/.markdownlint.yaml
.github/linters/.prettierrc.yaml
.github/linters/yaml-lint.yaml
.github/workflows/release.yml
.github/workflows/yamllint.yml
.gitignore
.golangci.yaml
.vscode/extensions.json
.vscode/settings.json
Makefile
config/certmanager/certificate.yaml
config/certmanager/kustomizeconfig.yaml
config/default/kustomization.yaml
config/prometheus/monitor.yaml
config/webhook/service.yaml
hack/observability/namespace.yaml
templates/cilium/cilium.yaml
templates/cluster-template-hcloud-network.yaml
templates/cluster-template-packer-hcloud-network.yaml
templates/cluster-template-packer-talos.yaml
templates/cluster-template-packer.yaml
templates/cluster-template.yaml

Adding Yaml Lint and linting files.
Use prettier in your IDE for automatic formatting. 
install yamllint on your machine and then check with make yamllint

:sparkles: Adding yamllint

---

README.md

Updating the support matrix for capi.

:book: Updating support matrix for capi v1.1.x

---

config/default/kustomization.yaml

Adds commonLabels to infrastructure components

:seedling: Adding commonLabels

---

api/v1beta1/types.go
go.mod
go.sum
pkg/csr/csr_suite_test.go
pkg/csr/csr_test.go
pkg/services/hcloud/loadbalancer/loadbalancer.go
pkg/services/hcloud/loadbalancer/loadbalancer_suite_test.go
pkg/services/hcloud/loadbalancer/loadbalancer_test.go
pkg/services/hcloud/placementgroup/placementgroup.go
pkg/services/hcloud/placementgroup/placementgroup_suite_test.go
pkg/services/hcloud/placementgroup/placementgroup_test.go
pkg/services/hcloud/server/server.go
pkg/utils/utils.go
pkg/utils/utils_suite_test.go
pkg/utils/utils_test.go

/kind cleanup
Adding unit tests and refactoring some utility functions.
**TODOs**:

:seedling: Adding unit tests and refactoring

---

.github/workflows/unit-test.yml
.github/workflows/verify-pr.yml
Makefile
README.md

Adding tests in github workflow. Also reverts make verify to run also lint.

:seedling: Adding tests in github workflow

---

pkg/services/hcloud/server/server.go
pkg/services/hcloud/server/server_suite_test.go
pkg/services/hcloud/server/server_test.go

/kind cleanup 
Adding unit tests for ```server.go```, small refactoring of ```createLabels``` function and fixing a bug in ```getSSHKeys``` which returned a slice with nil entries.
**TODOs**:

:seedling: Adding unit tests for server.go

---

controllers/csr_controller.go
controllers/hcloudmachine_controller.go
controllers/hetznercluster_controller.go
main.go

/kind cleanup  
Removing unused schemes from reconciler objects
**TODOs**:

:seedling: Removing unused schemes from reconciler objects

---

Makefile
Tiltfile

Fixing Makefile and Tiltfile by removing remains of unused deps.

:bug: Fixing Makefile and Tiltfile by removing remains of unused deps.

---

controllers/controllers_suite_test.go
controllers/hcloudmachine_controller_test.go
controllers/hetznercluster_controller_test.go

/kind cleanup 
Adding basic unit tests to make sure that reconciler works as intended
in a default setup. Refactoring some code in controller_tests for DRY
purposes.
**TODOs**:

:seedling: Add unit tests to cluster controller

---

api/v1beta1/conditions_const.go
controllers/controllers_suite_test.go
controllers/hetznercluster_controller.go
controllers/hetznercluster_controller_test.go
pkg/services/hcloud/client/fake/hcloud_client.go
pkg/services/hcloud/network/network.go

/kind clean-up 
Making sure that defining/enabling/disabling a network has the desired
effect. Using conditions to define cluster state.
**TODOs**:

:seedling: Add tests for controllers w/wo network

---

api/v1beta1/conditions_const.go
controllers/hetznercluster_controller.go
controllers/hetznercluster_controller_test.go

/kind cleanup
Adding conditions that load balancer is attached successfully as well as
unit tests checking for this condition.
**TODOs**:

:seedling: Add unit tests for load balancer in cluster controller

---

pkg/utils/utils.go
pkg/utils/utils_test.go

/kind bug 
Fixing error which returned the same diff twice. Adjusting the unit
tests which failed to find this bug due to a misuse of a Ginkgo
BeforeEach statement.
**TODOs**:

:bug: Fix error in difference of slices functions

---

api/v1beta1/conditions_const.go
controllers/controllers_suite_test.go
controllers/hetznercluster_controller.go
controllers/hetznercluster_controller_test.go

/kind cleanup
Add unit tests that test creating a cluster with and without placement
groups as well as updating its placement groups.
**TODOs**:

:seedling: Add unit tests for placement groups in controller

---

controllers/controllers_suite_test.go
controllers/hetznercluster_controller_test.go

/kind cleanup
Checking updates of name, of type and of extra targets
**TODOs**:

:seedling: Add unit tests for load balancer updates

---

api/v1beta1/hcloudmachine_types.go
api/v1beta1/hetznercluster_types.go
api/v1beta1/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml
controllers/hcloudmachine_controller_test.go
controllers/hetznercluster_controller_test.go

/kind cleanup
Testing the validation of our API with kubebuilder. Testing not setting
required values, wrong values, etc. Adding some additional kubebuilder
validations in the API
**TODOs**:

:seedling: Add tests of kubebuilder validation

---

pkg/services/hcloud/loadbalancer/loadbalancer.go

/kind bug
As the load balancer services in the API include one service we call
the kubeAPI service, we always have one service too much in the list. We
don't count this kubeAPI service in our list of ExtraServices, so that
we have to always consider slices of length len(lb.Services)-1.
**TODOs**:
- [] adds unit tests

:bug: Fix wrongly initialized slice of services

---

Makefile
templates/cluster-template-hcloud-network.yaml

Tests e2e without csr 
Fixes deletion of cluster in tilt

:seedling: Testing network e2e without csr

---

Makefile
docs/topics/quickstart.md
test/e2e/Makefile

update ccm version adds csi option in docs

:book: update ccm version adds csi option in docs

---

Makefile
docs/topics/quickstart.md
test/e2e/Makefile

:bug: fixing ccm-hcloud version

---

pkg/services/hcloud/client/client.go
pkg/services/hcloud/client/fake/fake_suite_test.go
pkg/services/hcloud/client/fake/hcloud_client.go
pkg/services/hcloud/client/fake/hcloud_client_test.go

/kind cleanup
Implements tests for fake HCloudClient and does small corrections and
bugfixes in the code of the fake client.
**TODOs**:

:seedling: Test fake HCloudClient

---

Makefile
config/rbac/role.yaml
controllers/hcloudmachine_controller.go
test/e2e/Makefile

/kind bug    
Fixes RBAC generation of the manager. Updates tilt to the newest version.

:seedling: Fixes rbac generation of manager and updates tilt dependency

---

Makefile
Tiltfile

/kind other           
Fixes the secret creation in tilt. Secrets are deleted along with cluster objects so we need to create everytime we want to create a cluster also a secret which contains the HCLOUD_TOKEN.

:seedling: Fixes secret creation in tilt, as the Hetzner secret is deleted along with the cluster objects

---

docs/topics/quickstart.md

/kind other       
Minor changes in the readme.

:book: Some minor changes to the readme.

---

README.md

Adds best practices badge from openssf see: https://bestpractices.coreinfrastructure.org/en/projects/5682

:seedling: Adds best practices badge from OpenSSF - Core Infrastructure Initiative

---

api/v1beta1/hetznerbaremetalmachine_types.go
types.md

/kind api-change
Updates API for install image

:seedling: Baremetal statemachine partitions

---

config/manager/controller_manager_config.yaml
config/manager/manager.yaml
main.go

/kind other     
Adds a health-check for the webhook-server

:seedling: Adding healthChecks for webhook server

---

Makefile
Tiltfile
templates/cluster-template-packer-talos.yaml
templates/node-image/talos-image/image.json

/kind bug         
* Updates talos in tilt
* Fixes the cluster-template of talos

:bug: Fixes Talos cluster-template and updates talos in tilt

---

Makefile

/kind feature        
Adds support for mulit-arch images. 
v1.0.0-alpha.12 got backport support for arm64.
Fixes #123

:sparkles: Support for multi-arch images

---

pkg/services/hcloud/server/server.go

/kind bug
don't check API readiness, isn't part of the Infrastructure provider.
(controlplane controller does)
#125 
**TODOs**:

🐛 fix: don't check API readiness

---

Makefile

/kind other      
This changes the ccm from ccm-hcloud to ccm-hetzner

:seedling: changing the ccm to ccm-hetzner

---

Makefile

changing image tag to latest for developing

:seedling: changing tag to latest in ccm

---

README.md
docs/README.md
docs/topics/node-image.md

/kind documentation  
Adds Documentation about how to use own node-images.

:book: Adding docs how to use own node-image

---

controllers/hcloudmachine_controller_test.go
pkg/services/hcloud/server/server.go

/kind other
Remove the check for an empty list of ssh keys to make sure everything
works with systems like Talos where you don't need ssh keys.
**Which issue(s) this PR fixes**
Fixes #137
**TODOs**:

:seedling: Remove check for empty list of ssh keys

---

.github/workflows/periodic-e2e.yaml

/kind other     
Adds a manual trigger to e2e tests

:seedling: Adding manual trigger to e2e

---

Makefile
api/v1beta1/hetznerbaremetalhost_types.go
api/v1beta1/hetznerbaremetalmachine_types.go
api/v1beta1/hetznerbaremetalmachine_webhook.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachinetemplates.yaml
controllers/hetznerbaremetalhost_controller.go
main.go
pkg/services/baremetal/baremetal/baremetal.go
pkg/services/baremetal/host/host.go
pkg/services/baremetal/host/host_test.go
pkg/services/baremetal/remediation/remediation.go
pkg/services/hcloud/server/server.go
templates/cluster-template-baremetal-control-planes.yaml

/kind other
Keep gocyclo <16 per function, follow go lint guidelines, refactor
some minor code parts
**TODOs**:

:seedling: Refactor bare metal code

---

Tiltfile
api/v1beta1/hcloudmachine_types.go
api/v1beta1/hcloudmachinetemplate_types.go
api/v1beta1/hetznerbaremetalhost_types.go
api/v1beta1/hetznerbaremetalmachine_types.go
api/v1beta1/hetznerbaremetalremediation_types.go
api/v1beta1/hetznerbaremetalremediationtemplate_types.go
api/v1beta1/hetznercluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediations.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediationtemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml
pkg/services/baremetal/host/host.go

/kind cleanup
Update the print columns of kubebuilder for multiple API objects. 
**TODOs**:

:seedling: Update kubebuilder print columns

---

controllers/hetznercluster_controller.go

/kind bug
Fix bug that prevented successful deletion of clusters in which there is no reference to a rescue ssh secret needed for bare metal.
**TODOs**:

:bug: Fix deleting of pure hcloud cluster

---

docs/developers/baremetal.md
docs/developers/development.md
docs/developers/tilt.md

Update developer docs
**TODOs**:

:book: Update developer docs

---

docs/developers/development.md
docs/topics/preparing-hetzner.md

Includes documentation about how to set up a project in Hetzner UI and related stuff.
**TODOs**:

:book: Update preparing Hetzner docs

---

.boilerplate.json
Tiltfile
test/e2e/capi_e2e_workload_upgrade_test.go

/kind other             
Fixes the Tiltfile formatting and ensure-boilerplate.

:seedling: Fixing verfiy

---

api/v1beta1/hetznerbaremetalhost_types.go

/kind cleanup
Follow suggestions by go-lint
**TODOs**:

:seedling: Follow lint suggestions

---

test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner.yaml

/kind failing-test     
Switching to nbg1

:bug: Switching to nbg

---

.github/workflows/pr-e2e.yaml

/kind cleanup           
Fixes e2e pr blocking for forks.

:seedling: Changing e2e PR workflow

---

docs/topics/preparation.md

📖 Removed "Third," (typo?)  

---

docs/topics/preparation.md

If you are new, and read the page one after the other, then you don't know yet, that ssh is only used for bare-metal servers.

📖  Added link to more detailed page "managing ssh keys"

---

docs/topics/preparation.md

📖 added two hyperlink to hcould-variables

---

test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner-talos.yaml
test/e2e/config/hetzner.yaml

/kind failing-test      CI test case is failing consistently.
Fixes failing caph upgrade test

:seedling: Fixing caph upgrade e2e test

---

.github/actions/e2e/action.yaml
Tiltfile
test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner-talos.yaml

/kind other     
Updates dependencies and prepares for the release v1.0.0-alpha.20

:seedling: updating dependencies

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md

/kind documentation    
* Fixes the table on the readme
Fixes #201

:book: Fixing readme and bug template

---

.github/actions/e2e/action.yaml
.github/workflows/e2e-basic-baremetal.yaml
.github/workflows/e2e-basic-packer.yaml
.github/workflows/e2e-basic.yaml
.github/workflows/e2e-periodic.yaml
.github/workflows/e2e-upgrade-caph.yaml
.github/workflows/pr-e2e.yaml
Makefile
docs/developers/development.md
hack/log/redact.sh
pkg/services/baremetal/baremetal/baremetal.go
templates/cluster-templates/bases/hetznerbaremetal-mhc-control-plane.yaml
templates/cluster-templates/bases/hetznerbaremetal-mhc-md-1.yaml
templates/cluster-templates/bases/hetznerbaremetal-mhc-rt-control-plane.yaml
templates/cluster-templates/bases/hetznerbaremetal-mhc-rt-md-1.yaml
test/e2e/Makefile
test/e2e/basic_baremetal_test.go
test/e2e/common.go
test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner.yaml
test/e2e/data/ccm/hcloud-ccm-hetzner.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/bases/crs-ccm-hetzner.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetzner-secret.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/cluster-template-hetzner-baremetal/kustomization.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/patches/cluster-hetzner_patch.yaml
test/e2e/e2e_suite_test.go

/kind other    
Adds e2e tests for baremetal

:seedling: Adding Baremetal e2e tests

---

test/e2e/data/infrastructure-hetzner/v1beta1/patches/hcloud-hetznerCluster-loadbalancer-off_patch.yaml

/kind other          
Fixes e2e for disable loadbalancer

:seedling: fixing lb e2e test

---

docs/reference/hetzner-cluster.md

/kind documentation   
Adds a section about using caph without hetzner loadbalancer.
**TODOs**:

:book: Adding section about using without hcloud loadbalancer

---

.github/workflows/e2e-feature-baremetal.yaml
Makefile
test/e2e/Makefile
test/e2e/basic_baremetal_test.go
test/e2e/basic_test.go
test/e2e/caph.go
test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts-raid.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/cluster-template-hetzner-baremetal-feature-raid-setup/kustomization.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/cluster-template-hetzner-baremetal-feature-raid-setup/md-1/kustomization.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/patches/hetznerbaremetal-mt-control-plane-ubuntu_patch.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/patches/hetznerbaremetal-mt-md-1-ubuntu_patch.yaml
test/e2e/feature_baremetal_test.go
test/e2e/feature_packer_test.go
test/e2e/feature_test.go

/kind cleanup           Adding tests, refactoring, fixing old bugs.
* Adds new baremetal Feature e2e test to ci
* Adds e2e test raid setup
**TODOs**:

:seedling: adds baremetal feature test for swraid

---

test/e2e/data/infrastructure-hetzner/v1beta1/cluster-template-hetzner-baremetal-feature-raid-setup/kustomization.yaml

/kind bug               
- Fixes e2e test raid setup by providing the necessary secret

:seedling: fix e2e test raid-setup

---

test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts-raid.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml

/kind failing-test      
* Changes wwn to healthy disk, removes on machine from inventory

:seedling: fix e2e baremetalhostinventory

---

Tiltfile
templates/node-image/talos-image/image.json

/kind other
The `talos-systems` GitHub organization was renamed to `siderolabs` due to legal reasons.
Fixes #305 
**TODOs**:

🌱 rename talos-systems to siderolabs

---

.github/workflows/coverage.yml
Makefile
Tiltfile
docs/developers/tilt.md
go.mod
go.sum
hack/ensure-boilerplate.sh
test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner.yaml

:seedling: update to clusterctl 1.2.3

---

CONTRIBUTING.md
docs/topics/advanced-caph.md

/kind documentation     
Fixes broken links

:book: Fixes broken links

---

Makefile
Tiltfile
docs/developers/tilt.md
go.mod
go.sum
test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner.yaml

/kind bug             
Fixes update of capi
Fixes #
**TODOs**:

:bug: fix capi-ci-config

---

.github/workflows/schedule-renovate.yaml

/kind other           
Fix update-bot
Fixes #
**TODOs**:

:bug: fix update-bot

---

.github/actions/metadata/action.yaml

/kind failing-test     
Fixes image build after action update
Fixes #
**TODOs**:

:seedling: fix image build

---

.github/renovate.json5
.github/renovate/approval.json5
.github/renovate/groups.json5
.github/workflows/pr-e2e.yaml
.github/workflows/pr-verify-renovate.yml
.github/workflows/schedule-renovate.yaml

/kind other         
Updates bot configuration
Fixes #
**TODOs**:

:seedling: update bot configuration

---

.github/workflows/pr-e2e.yaml
.github/workflows/pr-golangci-lint.yml
.github/workflows/pr-shellcheck.yml
.github/workflows/pr-starlark-lint.yml
.github/workflows/pr-unit-test.yml
.github/workflows/pr-verify-code.yml
.github/workflows/pr-verify-renovate.yml
.github/workflows/pr-yamllint.yml

/kind other      
update workflow to be not triggered by editing the PR title or body
Fixes #
**TODOs**:

:seedling: update workflow event

---

.github/workflows/schedule-link-checker.yml

/kind other 
Update lychee exclude statement.
**TODOs**:

:seedling: Update lychee cmd exclude statement

---

Makefile
hack/ci-e2e-capi.sh
test/e2e/Makefile

/kind bug               
Fixes ci tests after update of ginkgo v2
**TODOs**:

:bug: fix ci tests

---

README.md
test/e2e/data/shared/v1beta1/metadata.yaml

/kind other          
Adds the v1.3.x support for ci tests
**TODOs**:

:seedling: support capi v1.3.x

---

Makefile
config/manager/manager.yaml

/kind other           
Fixes minor release issues
Fixes #
**TODOs**:

:seedling: fix minor release issues

---

Makefile

/kind other    
fix release with cluster class
Fixes #
**TODOs**:

:seedling: fix release with cluster class

---

api/v1beta1/hetznercluster_webhook.go
api/v1beta1/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml
docs/reference/hetzner-cluster.md

/kind other
Adds the Location `hil`/Hillsboro and Network Zone `us-west` to the respective enums.
Fixes #
**TODOs**:

🌱 Add location Hillsboro/hil and network zone us-west 

---

.github/renovate/golang.json5

/kind other             
Fixes golang dep for update-bot
Fixes #
**TODOs**:

:seedling: fix golang dep for update-bot

---

.github/pull_request_template.md
.github/renovate.json5
.github/workflows/test.yml
hack/semver-upgrade.sh

/kind other             
- Fixes test workflow
- Fixes update-bot
Fixes #
**TODOs**:

:seedling: fixing update-bot and test workflow

---

.github/workflows/test.yml
.gitignore
Makefile
hack/golang-modules-update.sh
vendor/sigs.k8s.io/cluster-api/util/kubeconfig/kubeconfig.go
vendor/sigs.k8s.io/cluster-api/util/kubeconfig/testing.go

Fixes unit test
Fixes #
**TODOs**:

:seedling: fixing unit test

---

.github/workflows/test.yml
Makefile

- Fixes integration tests
Fixes #
**TODOs**:

:seedling: fixing integration test

---

.github/workflows/e2e-basic-baremetal.yaml
.github/workflows/e2e-basic-packer.yaml
.github/workflows/e2e-basic.yaml
.github/workflows/e2e-feature-baremetal.yaml
.github/workflows/e2e-feature.yaml
.github/workflows/e2e-periodic.yaml
.github/workflows/e2e-upgrade-caph.yaml
.github/workflows/e2e-upgrade-kubernetes.yaml

fixes the e2e test
Fixes #
**TODOs**:

:seedling: fixing e2e tests

---

.github/workflows/build.yml
.github/workflows/pr-e2e.yaml
.github/workflows/pr-lint.yml
.github/workflows/pr-verify.yml
.github/workflows/release.yml

Fixes nightly build
Fixes wrong checkout in CI
Fixes #
**TODOs**:

:seedling: fixing checkout and nightly build

---

.lychee.toml

Fix lychee toml 
Fixes #
**TODOs**:

:seedling: fix lychee toml

---

.github/workflows/schedule-link-checker.yml
.lychee.toml
Makefile
README.md

Fixes the lychee link checker after the update
Fixes #
**TODOs**:

:seedling: fix lychee workflow

---

.github/workflows/build.yml
.github/workflows/release.yml

Fixes break of cosign since v2 update
Fixes #
**TODOs**:

:seedling: fix cosign upgrade

---

.github/renovate/approval.json5
.github/renovate/golang.json5

disable update of controller-runtime minor and automatic update of cluster-api
Fixes #
**TODOs**:

:seedling: disables some automatic updates

---

.github/workflows/release.yml

This fixes the github action workflow for the release procedure
Fixes #
**TODOs**:

:seedling: fix release workflow

---

.github/workflows/release.yml

Fixes permission for release workflow
Fixes #
**TODOs**:

:seedling: fix permissions for release workflow

---

controllers/hcloudmachinetemplate_controller.go
controllers/hetznerbaremetalmachine_controller.go
controllers/hetznerbaremetalremediation_controller.go
pkg/scope/baremetalmachine.go
pkg/scope/requeue_error.go
pkg/services/baremetal/baremetal/baremetal.go
pkg/services/baremetal/baremetal/baremetal_suite_test.go

Mainly updating imports to align them and error handling
**TODOs**:

:seedling: Update code of bm controller

---

controllers/hetznerbaremetalhost_controller_test.go
controllers/hetznerbaremetalmachine_controller_test.go
controllers/hetznercluster_controller_test.go
pkg/scope/machine.go
pkg/services/hcloud/server/server.go
pkg/services/hcloud/server/server_test.go

Use standard library for errors, refactor code.
**TODOs**:

:seedling: Refactor code of server package

---

Makefile
Tiltfile
docs/topics/production-environment.md

The namespace has been changed but not updated in Tilt. The config map has to be removed.
**TODOs**:

:bug: Fix Tilt

---

.github/renovate/groups.json5

Fixes Update Bot 
Fixes #
**TODOs**:

:seedling: fix update-bot builder image

---

.github/workflows/pr-verify.yml

Fixes Ci workflow which didn't run again after correcting the PR Title
Fixes #
**TODOs**:

:bug: fix workflow for wrong PR types

---

pkg/services/baremetal/baremetal/baremetal.go
pkg/services/baremetal/host/host.go
pkg/services/baremetal/host/state_machine.go
pkg/services/hcloud/loadbalancer/loadbalancer.go
pkg/services/hcloud/machinetemplate/machinetemplate.go
pkg/services/hcloud/network/network.go
pkg/services/hcloud/placementgroup/placementgroup.go
pkg/services/hcloud/remediation/remediation.go
pkg/services/hcloud/server/server.go
pkg/services/hcloud/util/utils.go

Handle rate limits everywhere where HCloud or robot API is called. Use a utility function to reduce code. Additionally, there is some refactoring of SSH key validation
**TODOs**:

:bug: Fix rate limit handling and refactoring SSH validation

---

api/v1beta1/hetznerbaremetalhost_types.go
pkg/services/baremetal/host/host.go
pkg/services/baremetal/host/host_test.go

Update and facilitate reboot logic. Remove some states that are not required.
**TODOs**:

:seedling: Update host reboot logic

---

Makefile

Remove `$(SUDO)` in the Makefile, since it had no effect.

:seedling: In Makefile remove "$(SUDO)"

---

api/v1beta1/types.go
pkg/services/hcloud/loadbalancer/loadbalancer.go
pkg/services/hcloud/loadbalancer/loadbalancer_test.go

Updating code of load balancer library to make it easier to read and understand. Fixing error that load balancer type was translated wrongly from the value in the spec of HetznerCluster to the load balancer create options. Adding further unit tests.
**TODOs**:

:bug: Fix wrong lb type

---

pkg/services/hcloud/network/network.go
pkg/services/hcloud/network/network_test.go

Add unit tests, refactor code
**TODOs**:

:seedling: Update code of pkg network

---

api/v1beta1/hetznercluster_types.go
api/v1beta1/hetznercluster_types_test.go
api/v1beta1/tags.go
api/v1beta1/zz_generated.deepcopy.go
controllers/controllers_suite_test.go
controllers/hcloudmachine_controller_test.go
controllers/hetznercluster_controller_test.go
pkg/services/hcloud/loadbalancer/loadbalancer.go
pkg/services/hcloud/loadbalancer/loadbalancer_test.go
pkg/services/hcloud/network/network.go
pkg/services/hcloud/placementgroup/placementgroup.go
pkg/services/hcloud/placementgroup/placementgroup_test.go
pkg/services/hcloud/server/server.go
pkg/services/hcloud/server/server_test.go
test/helpers/defaults.go

Updating code of placement group package to make it easier to read. Addingt function ClusterTagKey as method on HetznerCluster. Adding unit tests in api folder
**TODOs**:

:seedling: Update code of placement group pkg

---

pkg/scope/machine.go
pkg/services/hcloud/server/server.go
pkg/services/hcloud/server/server_test.go

Updating code of hcloud/server to improve readability
**TODOs**:

:seedling: Update code of package hcloud/server

---

controllers/csr_controller.go
pkg/csr/csr.go
pkg/csr/csr_suite_test.go
pkg/csr/csr_test.go

Updating code of pkg csr to make it more readable.
**TODOs**:

:seedling: Update code of pkg csr

---

Makefile

This PR adds `make watch` which shows the state of the machines and the latest events.

:seedling: add `make watch`

---

pkg/scope/baremetalremediation.go
pkg/services/baremetal/remediation/remediation.go
pkg/services/baremetal/remediation/remediation_test.go

Refactoring code, adding unit tests, adding events in case something goes wrong.
**TODOs**:

:seedling: Refactor code of bm remediation pkg

---

docs/topics/node-image.md

Fixes broken links to `image.json`
**What this PR does / why we need it**: Fixes broken links in the documentation

📖 Fixes broken links

---

docs/README.md
docs/topics/upgrade.md

Added docs for upgrading to latest version of CAPH.

:book: Added Upgrade Guide.

---

README.md

Update the docs, so that they are easier to understand for new users.

:book: updated docs (README)

---

pkg/scope/cluster.go

:seedling: fix comment.

---

.envrc.sample
.gitignore
Makefile
docs/developers/development.md
hack/filter-caph-controller-manager-logs.py
hack/get-kubeconfig-of-workload-cluster.sh
hack/output-for-watch.sh
hack/tail-caph-controller-logs.sh

this PR improves `make watch`:
> show IP of first control-plane, show if wl-cluster is reachable.

:seedling: improved `make watch`

---

.golangci-suggestions.yaml
.golangci.yaml
pkg/services/baremetal/host/action_result.go
pkg/services/baremetal/host/host.go
pkg/services/baremetal/host/host_suite_test.go
pkg/services/baremetal/host/host_test.go
pkg/services/baremetal/host/state_machine.go
pkg/services/baremetal/host/utils.go
pkg/services/baremetal/host/utils_test.go

Following linting suggestions in host pkg. Adding unit tests and utility functions.
**TODOs**:

:seedling: Follow linting suggestions in host pkg

---

.golangci.yaml
.lychee.toml
api/v1beta1/hcloudremediation_webhook.go
api/v1beta1/hcloudremediationtemplate_webhook.go
api/v1beta1/hetznerbaremetalhost_webhook.go
api/v1beta1/hetznerbaremetalremediation_webhook.go
api/v1beta1/hetznerbaremetalremediationtemplate_webhook.go
controllers/hcloudmachine_controller.go
controllers/hcloudmachinetemplate_controller.go
controllers/hcloudremediation_controller.go
controllers/hetznerbaremetalhost_controller.go
controllers/hetznerbaremetalmachine_controller.go
controllers/hetznerbaremetalremediation_controller.go
controllers/hetznercluster_controller.go
main.go
pkg/scope/baremetalhost.go
pkg/scope/baremetalmachine.go
pkg/scope/baremetalremediation.go
pkg/scope/cluster.go
pkg/scope/hcloudmachinetemplate.go
pkg/scope/hcloudremediation.go
pkg/scope/machine.go
pkg/services/baremetal/baremetal/baremetal.go
pkg/services/baremetal/client/mocks/factory.go
pkg/services/baremetal/client/ssh/ssh_client.go
pkg/services/hcloud/client/client.go
pkg/services/hcloud/client/fake/hcloud_client.go
pkg/services/hcloud/server/server.go

The CI did not trigger checks for linting. This is why the current main branch fails to comply to our linting rules. This PR fixes that.
**TODOs**:

:seedling: Fix linting

---

pkg/services/baremetal/client/robot/credentials.go
pkg/services/baremetal/client/ssh/ssh_client.go
pkg/services/hcloud/remediation/remediation.go
pkg/services/hcloud/remediation/remediation_test.go

Refactoring code of hcloud remediation to make it easier to read, add unit tests, update minor things in other packages.
**TODOs**:

:seedling: Refactor code of hcloud remediation

---

.github/workflows/pr-lint.yml

🌱 Enable linting on Pull Requests
Fixes #838 
Checked this on a fork [here](https://github.com/kranurag78/cluster-api-provider-hetzner/actions/runs/5467603164/jobs/9954128184)
**TODOs**:

🌱 Enable linting on pull requests

---

Makefile

:bug: fix kubectl in Makefile.

---

docs/topics/preparation.md

A small typo in the docs about environment variable exporting.
Untracked
**TODOs**:

📖 fix(docs): unrequired trailing slash for env var export

---

Makefile
hack/output-for-watch.sh

Improve `make watch`:
* Show External IPs of nodes
* ❌ Warn, if there are not enough nodes in the wl-cluster.

:seedling: better `make watch`

---

README.md
docs/developers/releasing.md
docs/topics/quickstart.md

Improve the documentation.
Here is the rendered preview of [README.md](https://github.com/syself/cluster-api-provider-hetzner/blob/tg/improve-docs/README.md)

:book: Improve documentation.

---

README.md

Added in the k8s version table that we support k8s 1.26 and 1.27 too.
Fixes #
**TODOs**:

:book: updated README.md k8s version table

---

.github/workflows/schedule-update-bot.yaml
hack/upgrade-builder-image.sh

**What this PR does / why we need it**
- upgrades the scripts. [ref](https://github.com/syself/cluster-api-provider-hetzner/pull/862#issuecomment-1660088852)
Fixes #
- add a new target in Makefile 
```make
variable:
echo "variable:"$(BUILDER_IMAGE_VERSION)""
```
Invoke the target
```bash
$ make variable                                                                      
echo "variable:"1.0.7""
variable:1.0.7
```
**TODOs**:

🌱 update upgrade script

---

pkg/services/hcloud/remediation/remediation.go

In case there is no server, we get a nil server by hcloud-go and not an error. We didn't handle this case until now, which let to nil pointer errors, if we try to reboot an empty server.
**TODOs**:

:bug: Handle nil server in remediation

---

main.go

If the current state does not match the desired state, we want to act soon.
We reduce the periodic syncing to 3 minutes by default.
You can change this with the new command line argument.
Please provide feedback, if this is causing you issues (or if you like this change).

:seedling: add `-sync-period` option. Default 3min

---

api/v1beta1/conditions_const.go
controllers/hetznercluster_controller.go
controllers/hetznercluster_controller_test.go
pkg/services/baremetal/host/host.go
pkg/services/hcloud/util/utils.go

Refactoring rate limit condition so that it shows positive result if things are positive and negative results otherwise.
**TODOs**:

:seedling: Refactor rate limit condition

---

api/v1beta1/conditions_const.go
controllers/hetznerbaremetalhost_controller.go
controllers/hetznerbaremetalhost_controller_test.go
controllers/hetznercluster_controller.go
controllers/hetznercluster_controller_test.go
pkg/services/baremetal/host/host.go
pkg/services/baremetal/host/state_machine.go
pkg/services/hcloud/network/network.go

Add suffix to Conditions and Reasons
Related:
https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20200506-conditions.md#data-model-changes

:seedling: Add suffix to Conditions and Reasons

---

api/v1beta1/conditions_const.go
controllers/hcloudmachine_controller.go
controllers/hcloudmachine_controller_test.go
controllers/hcloudmachinetemplate_controller.go
controllers/hcloudremediation_controller.go
controllers/hetznerbaremetalmachine_controller.go
controllers/hetznercluster_controller.go
controllers/hetznercluster_controller_test.go

don't set InstanceReady.
And use MarkTrue if everything is fine.

:seedling: set HCloudTokenAvailableCondition

---

api/v1beta1/conditions_const.go
controllers/hcloudmachine_controller.go
controllers/hcloudmachinetemplate_controller.go
controllers/hcloudremediation_controller.go
controllers/hetznerbaremetalmachine_controller.go
controllers/hetznercluster_controller.go
pkg/services/hcloud/client/client.go
pkg/services/hcloud/server/server.go

Fix condition for wrong hcloud token and add further condition for missing ssh key
**TODOs**:

:bug: Fix conditions for wrong hcloud token and other conditions

---

pkg/services/hcloud/client/client.go

Handle unauthorized for HCloudMachineTemplate and
HetznerBareMetalMachine as well
**TODOs**:

:bug: Handle remaining unauthorized

---

docs/developers/updating-kubernetes-version.md
hack/boilerplate/boilerplate.py

:seedling: fix typo

---

api/v1beta1/conditions_const.go
controllers/hetznerbaremetalhost_controller.go
controllers/hetznerbaremetalhost_controller_test.go
pkg/services/baremetal/host/host.go
pkg/services/baremetal/host/state_machine.go

Refactoring conditions for HetznerBareMetalHost objects to make them more precise, to improve the namings and to include a summary condition
**TODOs**:

:seedling: Refactor conditions for HetznerBareMetalHosts

---

controllers/controllers_suite_test.go
controllers/hcloudmachine_controller_test.go
controllers/hetznercluster_controller_test.go

Refactoring tests to remove unused code, to re-use objects better and to make the code more readable
**TODOs**:

:seedling: Refactor tests of hetznercluster controller

---

controllers/hetznerbaremetalmachine_controller_test.go

Refactoring tests for hetznerbaremetalmachine controller to make them more readable, to remove unnecessary code and to re-use objects across tests
**TODOs**:

:seedling: Refactor hetznerbaremetalmachine-controller tests

---

controllers/hcloudmachinetemplate_controller_test.go
controllers/hetznerbaremetalhost_controller_test.go
controllers/hetznercluster_controller_test.go
pkg/services/hcloud/client/fake/hcloud_client.go

Refactoring remaining controller tests as well as fixing some bugs in HCLoud client that caused instability of the tests.
Namely there was a problem in generating IDs, that let to a specific situation in which we overwrite saved HCloud objects with new objects.
**TODOs**:

:seedling: Refactor controller tests and fake HCloud client

---

pkg/services/baremetal/host/host_test.go
pkg/services/baremetal/host/state_machine_test.go
pkg/services/baremetal/host/utils_test.go
pkg/services/hcloud/server/server_test.go
pkg/services/hcloud/util/utils_test.go
pkg/utils/utils_test.go

Refactoring unit tests - mostly improving table-driven test inputs
**TODOs**:

:seedling: Refactor unit tests

---

pkg/services/baremetal/host/host.go

🐛 Don't use server number in the error message

---

controllers/hetznerbaremetalmachine_controller_test.go

✨ Add hetznerbaremetal machine webhook tests

---

controllers/controllers_suite_test.go
controllers/hcloudmachine_controller.go
controllers/hcloudmachinetemplate_controller.go
controllers/hcloudremediation_controller.go
controllers/hetznerbaremetalhost_controller.go
controllers/hetznercluster_controller.go
controllers/hetznercluster_controller_test.go
main.go
test/helpers/envtest.go

✨ Add flag for HCloud rate limitting

---

api/v1beta1/hetznerbaremetalhost_webhook.go

✨ Add webhook for hetzner baremetal host server ID

---

pkg/services/baremetal/remediation/remediation.go

🐛Don't reboot if HetzerBareMetalMachine not found

---

pkg/services/baremetal/remediation/remediation.go

🐛 Rename HetznerBareMetalMachine to HetznerBareMetalHost

---

pkg/services/baremetal/host/host.go

testing rate limit for bare metal
**TODOs**:

:seedling: Handle weird rate limit exceeded error of robot API

---

pkg/services/hcloud/client/client.go

Adds the metrics `hcloud-go` exposes to the registry serving `localhost:8080/metrics`.
**Which issue(s) this PR fixes**
Related to #831 
The type assertion that I used is a bit icky and _MAY_ break in future controller-runtime versions. In that case the metrics would stop being available.
One possible alternative to the type assertation would be, to create our own Registry to be used by all hcloud-go clients and use `metrics.Registry.MustRegister(hcloudClientRegistry)` to make the metrics available.
We could create a new registry per client we create, but I think that would leak memory (and CPU cycles)  
**TODOs**:

✨ Add metrics from hcloud-go

---

api/v1beta1/hetznerbaremetalhost_webhook.go
controllers/hetznerbaremetalhost_controller_test.go
controllers/hetznerbaremetalmachine_controller_test.go
main.go
pkg/services/baremetal/host/host_suite_test.go
pkg/services/baremetal/host/host_test.go
test/helpers/defaults.go
test/helpers/envtest.go

✨ Add webhook to check if same serverID baremetal host exist or not

---

pkg/services/baremetal/host/host.go

Update host also when reconcile returns an error
**TODOs**:

:bug: Update host on error

---

api/v1beta1/hcloudmachinetemplate_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml
controllers/hcloudmachinetemplate_controller.go
controllers/hcloudmachinetemplate_controller_test.go
go.mod

✨ Handle HCloudMachineTemplate controller clusterclass as a owner

---

pkg/services/baremetal/host/host.go

Adding a timeout after every reboot so that it does not trigger another
reboot within the first (milli)seconds.
This fixes the issue that always a hardware reboot was triggered right
after the software reboot.
**TODOs**:

:bug: Add timeout to fix bug that hardware reboot is triggered right after software reboot

---

controllers/hcloudmachine_controller.go

Ignore cluster condition updates when enqueueing events.
Related to #926 
**TODOs**:

🌱 ignore cluster condition updates when enqueueing events

---

api/v1beta1/conditions_const.go
pkg/services/hcloud/server/server.go

🐛 Add condition for server rate limit exceed while creating hcloud servers

---

pkg/services/baremetal/remediation/remediation.go

Currently, the controller reboots servers even though their respective HetznerBareMetalHosts are in maintenance mode. This leads to the fact that maintenance mode does not work as expected.
This commit adapts the
remediation strategy for hosts in maintenance mode to not reboot them.
Fixes #930 
**TODOs**:

:bug: Handle remediation of hosts in maintenance

---

controllers/hcloudmachine_controller_test.go

Add tests for the predicate introduced in #934
**Which issue(s) this PR fixes**: -
**Special notes for your reviewer**: -
**TODOs**:

🌱 add unit tests for IgnoreHetznerClusterConditionUpdates

---

.golangci.yaml
controllers/csr_controller.go

Deny old CSR to remove them more quickly
**TODOs**:

:sparkles: Deny old CSR

---

Tiltfile
hack/version.sh
main.go
pkg/services/hcloud/client/client.go
pkg/version/version.go

This commit adds versioning information to the controller when it starts.
Fixes #
**Special notes for your reviewer**
**TODOs**:

✨ add versioning information to controller

---

pkg/services/baremetal/host/host.go
pkg/services/hcloud/util/utils.go

Debug rate-limiting issue.
If we provision several baremetal server and the ssh-key already exists, rate-limit gets reached.

:sparkles: debug rate-limiting

---

.github/workflows/schedule-update-bot.yaml

Fixes an issue with mounting the docker socket when running the update bot.
Fixes #
**TODOs**:

:bug: fix update bot mounting docker socket

---

api/v1beta1/hetznerbaremetalmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml
controllers/hetznerbaremetalmachine_controller.go
controllers/hetznerbaremetalmachine_controller_test.go
pkg/services/baremetal/baremetal/baremetal.go

✨ Add new API status for the HetznerBareMetalMachineStatus

---

api/v1beta1/conditions_const.go
controllers/hetznerbaremetalhost_controller.go
controllers/hetznerbaremetalmachine_controller_test.go
pkg/services/baremetal/baremetal/baremetal.go
pkg/services/baremetal/host/host.go

✨ Add new condition for the hetznerbaremetal machine

---

api/v1beta1/hetznerbaremetalhost_types.go
api/v1beta1/hetznerbaremetalmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml

Rename "Consumer" to "HetznerBareMetalMachine"
Exampel:
```
❯ k get hbmh
NAME          STATE   IPV4            IPV6                 MAINTENANCE   CPU   RAM   **CONSUMER**   AGE   REASON              MESSAGE
test-bm-gpu           95.216.111.98   2a01:4f9:2b:dc8::1   true          8     64                   55m   
```

:seedling: HetznerBareMetalHost: rename "Consumer" to hbmm

---

.github/workflows/pr-lint.yml
.yamllint.yaml
api/v1beta1/hcloudmachine_types.go
api/v1beta1/hetznerbaremetalmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml
controllers/hetznerbaremetalmachine_controller.go
pkg/services/baremetal/baremetal/baremetal.go

Fix lint workflow
Fixes #
**TODOs**:

:seedling: fix lint workflow

---

pkg/services/baremetal/remediation/remediation.go

There was a bug where the remediation object is there for a HetznerBareMetalMachine that has no host attached. This commit handles this case and stops remediation instead of returning an error.
**TODOs**:

:bug: Fix bm remediation if no host attached

---

Makefile
docs/topics/quickstart.md
test/e2e/data/ccm/hcloud-ccm-hetzner.yaml
test/e2e/data/ccm/hcloud-ccm-network.yaml

Updates ccm version to the latest version
Fixes #
**TODOs**:

:seedling: update ccm version

---

Tiltfile

Signed-off-by: Anurag <81210977+kranurag7@users.noreply.github.com>
Fixes #
**TODOs**:

🌱 fix Tiltfile

---

Makefile

This commit adds a new helm target and uses the same afterward.
Fixes #
**TODOs**:

🌱 add helm target to Makefile

---

.github/workflows/schedule-update-bot.yaml

We want to update .builder-image.version.txt using renovate bot and this commit fixes that.
Fixes #
**TODOs**:

🌱 include .builder-image-version.txt in filters

---

.github/renovate/groups.json5

🌱 update bot timings

---

.github/workflows/pr-verify.yml

this commit removes multiple steps of validating renovate config and uses a loop to traverse over all files with *.json5 extension for validation.
Fixes #
**TODOs**:

🌱 aviod multiple steps of validating renovate config

---

CONTRIBUTING.md

Update contribution guidelines that are in some parts only relevant for the Cluster API Prow flows and to add some important information helpful for contributors.
**TODOs**:

:seedling: Update contribution guidelines

---

controllers/hetznercluster_controller.go
go.mod
go.sum
vendor/github.com/docker/docker/api/swagger.yaml
vendor/github.com/docker/docker/api/types/filters/parse.go
vendor/github.com/docker/docker/api/types/versions/compare.go
vendor/modules.txt

Ref: https://github.com/syself/cluster-api-provider-hetzner/security/dependabot/26
Fixes #
**TODOs**:

🌱 bump docker/docker to address security alert

---

.github/workflows/pr-lint.yml

enable this to trigger multiple times not only once.
Fixes #
**TODOs**:

🌱 fix lint workflow

---

Makefile
hack/verify-manifests.sh

This commit adds verify-manifests.sh scripts inside hack directory.
Part of: https://github.com/syself/cluster-api-provider-hetzner/pull/852
Fixes #
**TODOs**:

🌱 Add verify script

---

.envrc.sample
Makefile

🌱 remove unused make targets

---

.github/labeler.yaml

🌱 use v5 version of labeler

---

hack/ci-e2e-get-token.sh

We update `.envrc` manually on expiration of token, and this commit updates the script to update the `.envrc` and load the environment variable automatically.
Fixes #
**TODOs**:

🌱 update script to update .envrc

---

docs/topics/upgrade.md

- Updated the doc with two small grammatical changes.
Fixes #
**TODOs**:

🌱 Update upgrade.md

---

test/e2e/basic_baremetal_test.go
test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner.yaml
test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml

🌱 fix e2e baremetal tests

---

README.md

Minor fixes in Readme.md.
Fixes #
**TODOs**:

🌱 Update README.md

---

.github/workflows/build.yml

🌱 attest sbom for caph staging image

---

docs/topics/quickstart.md

Basic structure changes of the quickstart Hetzner doc.
Fixes 
This PR is one of the many PRs that will be created to fix the #1126 issue. 
**TODOs**:

🌱 Update quickstart.md

---

docs/topics/quickstart.md

Fix regarding structure and flow of the guide
Fixes #
**TODOs**:

:book: Update quickstart.md

---

pkg/services/baremetal/host/host.go

Names of storage devices might change after reboot. We stored the names in the host object and didn't update them anymore. However, these names might change after a reboot and might even switch between devices.
This led to the issue that the wwn that the users give as reference to the storage device that is used in provisioning did not correspond anymore to the name of the device that we stored in the host object.
This led to the operator using the wrong storage device in provisioning.
Now we get the latest information of wwn and storage device names before installimage and thus always take the correct storage device for provisioning.
**TODOs**:

:bug: Fix wrong names of storage devices

---

hack/boilerplate/boilerplate.py
hack/boilerplate/boilerplate.py.txt
hack/boilerplate/boilerplate_test.py
hack/boilerplate/testdata/default/fail.py
hack/boilerplate/testdata/default/pass.py
hack/boilerplate/testdata/with_config/fail.py
hack/boilerplate/testdata/with_config/pass.py
hack/filter-caph-controller-manager-logs.py

this PR updates the python shebang to python3 to work with distos which have no python symlink. 
Fixes #1142 
**TODOs**:

:seedling: update python shebang to python3

---

docs/topics/preparation.md

Updated the structure and flow of the sentences and corrected the grammatical errors.
Fixes #
**TODOs**:

:book: Update preparation.md

---

docs/topics/upgrade.md

:book: Update upgrade.md

---

docs/topics/advanced-caph.md

Fixed structural, flow, and grammatical errors
Fixes #
**TODOs**:

:book: Update advanced-caph.md

---

docs/reference/hetzner-bare-metal-host.md

Minor fixes
Fixes #
**TODOs**:

:book: Update hetzner-bare-metal-host.md

---

api/v1beta1/hcloudmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml

Added descriptions
Fixes #
**TODOs**:

🌱 Update hcloudmachine_types.go

---

.github/workflows/release.yml

🌱 attest sbom to release image

---

api/v1beta1/hetznercluster_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml

Added spec descriptions.
Fixes #
**TODOs**:

🌱 Update hetznercluster_types.go

---

api/v1beta1/hetznerbaremetalremediation_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediations.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediationtemplates.yaml

Added spec description.
Fixes #
**TODOs**:

🌱 Update hetznerbaremetalremediation_types.go

---

controllers/hetznercluster_controller.go

Update the secret in the workload cluster whenever the secret in the management cluster is changed.
Closes #1168
- I removed the `immutable` field. The current code set it to `false` anyway. If this was ever set to `true`, there can still be workload clusters with an immutable secret. I can add some code to delete the secret first if that is the case.
- This is not covered by any tests. I did not find any existing `envtest` tests that mocked the Workload Cluster API.
- I used `controllerutil.CreateOrUpdate` to reconcile the secret in the workload cluster. I hope this was fine, you had no existing usages of this helper in the repo but other methods from `controllerutil` were in …

:sparkles: Keep secret in workload cluster in sync

---

api/v1beta1/hetznerbaremetalhost_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml

Added spec descriptions and fixes.
Fixes #
**TODOs**:

🌱 Update hetznerbaremetalhost_types.go

---

api/v1beta1/remediation_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudremediations.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudremediationtemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediations.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediationtemplates.yaml

Added spec descriptions
Fixes #
**TODOs**:

🌱 Update remediation_types.go

---

api/v1beta1/hetznerbaremetalmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml

Spec descriptions and fixes.
Fixes #
**TODOs**:

🌱 Update hetznerbaremetalmachine_types.go

---

api/v1beta1/types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml

Added spec description and fixes.
Fixes #
**TODOs**:

🌱 Update types.go

---

.github/workflows/pr-lint.yml
.golangci.yaml
api/v1beta1/hcloudmachine_types.go
pkg/services/baremetal/remediation/remediation.go
pkg/services/hcloud/remediation/remediation.go

🌱 Added for import aliases for kubernetes packages

---

.github/workflows/test.yml

Ref: https://github.com/syself/cluster-api-provider-hetzner/blob/4cf38c7a39e76e451ab5c18fddf946c2ff3a3532/.github/workflows/pr-lint.yml#L5

🌱 run tests on draft PRs

---

api/v1beta1/hcloudmachine_types.go
api/v1beta1/hcloudremediation_types.go
api/v1beta1/hcloudremediationtemplate_types.go
api/v1beta1/hetznerbaremetalhost_types.go
api/v1beta1/hetznerbaremetalmachine_types.go
api/v1beta1/hetznerbaremetalmachinetemplate_types.go
api/v1beta1/hetznerbaremetalremediation_types.go
api/v1beta1/hetznerbaremetalremediationtemplate_types.go
api/v1beta1/hetznercluster_types.go
api/v1beta1/hetznerclustertemplate_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudremediations.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudremediationtemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachinetemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediations.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediationtemplates.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml

🌱 update shortnames for caph objects

---

controllers/hetznerbaremetalhost_controller_test.go

🐛Fix flaky reach state image installing test

---

docs/topics/upgrade.md

update upgrade guide with v1.6.0 and v1.6.3 and some rephrasing as well.

🌱 update CAPH upgrade docs

---

.gitignore
Makefile

This file is not used anymore.

:seedling: remove tilt-settings.json from comments.

---

api/v1beta1/hetznerbaremetalhost_types.go
go.mod
pkg/services/baremetal/host/host.go

We have seen that machines get rebooted again and again.
We want to have more detailed events, so that we can debug that.

:seedling: Create more detailed events about rebooting BM.

---

docs/developers/releasing.md

Added instructions to releasing.md

:seedling: Added instructions to releasing.md

---

README.md

🌱 update compatibility matrix in the README

---

README.md

:seedling: add link to readme

---

CONTRIBUTING.md
README.md

Replaces URL to the hosted docs
Fixes #
**TODOs**:

:seedling: replacing docs url

---

README.md

🐛Fix broken link in readme

---

.github/workflows/pr-lint.yml

Trigger event was not matching
Fixes #
**TODOs**:

:bug: Fixes trigger for linter

---

pkg/services/hcloud/loadbalancer/loadbalancer.go

🐛Fix loadbalancer deleting bug

---

.github/ISSUE_TEMPLATE/config.yaml

Adds more contact information to the issues
Fixes #
**TODOs**:

:seedling: Adding contact information

---

README.md

🌱 Change order and add new article

---

README.md

Add a missing banner linking to syself.com/demo
Fixes #
**TODOs**:

:seedling: add missing banner

---

Makefile
Tiltfile
docs/caph/04-developers/02-tilt.md
go.mod
go.sum
test/e2e/config/hetzner-ci.yaml
test/e2e/config/hetzner.yaml
vendor/github.com/docker/docker/api/swagger.yaml
vendor/modules.txt
vendor/sigs.k8s.io/cluster-api/api/v1beta1/cluster_phase_types.go
vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/client/config/cert_manager_client.go
vendor/sigs.k8s.io/cluster-api/controllers/remote/cluster_cache_tracker.go
vendor/sigs.k8s.io/cluster-api/test/e2e/clusterctl_upgrade.go
vendor/sigs.k8s.io/cluster-api/test/e2e/self_hosted.go
vendor/sigs.k8s.io/cluster-api/test/framework/autoscaler_helpers.go
vendor/sigs.k8s.io/cluster-api/test/framework/deployment_helpers.go
vendor/sigs.k8s.io/cluster-api/test/framework/resourceversion_helpers.go

Upgrade from CAPI 1.7.4 to 1.7.5

:seedling: Upgrade to capi 1.7.5

---

README.md

Remove Old Kubernetes Versions
Fixes #
**TODOs**:

:seedling: remove old kubernetes versions

---

controllers/hcloudmachine_controller_test.go

🌱Add tests for PR 1413

---

pkg/services/baremetal/client/ssh/detect-linux-on-another-disk.sh

Fixes #1216
Better usage message for detect-linux-on-another-disk.sh

:seedling: Better usage message for detect-linux-on-another-disk.sh

---

controllers/hcloudmachine_controller_test.go

This tests often fails in CI.
> [It] creates the HCloud machine in Hetzner 1 (flaky)
I will have a look and it now.
Example: https://github.com/syself/cluster-api-provider-hetzner/actions/runs/10449780765/job/28932786187?pr=1440#step:7:2032
This PR adds logging, so that we can better understand the root cause.

:seedling: Better logging, to find root cause of flaky test.

---

.github/workflows/pr-lint.yml
.github/workflows/pr-verify.yml

Draft PRs should be checked by the linters, too.

:seedling: Lint PRs in Draft-mode, too.

---

.github/workflows/pr-lint.yml
.github/workflows/pr-verify.yml

Always lint and verify in GithubActions.

:seedling: Always lint and verify in GithubActions.

---

pkg/services/baremetal/client/ssh/nic-info.sh
pkg/services/baremetal/client/ssh/ssh_client.go
pkg/services/baremetal/host/host.go

Fixes #1523
Additionally: Before the PR the shell script was inside the Go source code. The code was moved to a new file. This is much better when testing the script.

🐛 wip nic-info.sh

---

templates/cluster-templates/bases/kct-md-0-ubuntu.yaml

Fixed indentation issue in ubuntu base cluster template manifest.

🐛 Fix indentation in cluster template

---

pkg/services/baremetal/client/ssh/ssh_client.go

See https://github.com/bramvdbogaerde/go-scp/pull/88
And related update to the docs:
https://github.com/bramvdbogaerde/go-scp/commit/c2410915e3da161dcf056b6486f5401eb3819b48#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R81

:seedling: fix usage of scp packge.

---

.github/workflows/pr-e2e.yaml
.github/workflows/pr-lint.yml
.github/workflows/pr-verify.yml

pull_request_target creates a lot of difficulties.

:seedling: Remove "pull_request_target" from Github Workflows.

---

.github/workflows/pr-e2e.yaml
.github/workflows/pr-verify.yml
.vscode/settings.json

update pr-verify.yml to be self-contained.
Fix that pr-verify does not work for PRs from forks.
Skip steps which are not strictly needed (if fork)
Better err msg, when e2e tests fail (if fork).

🌱Make "Verify Pull Request" work on forks.

---

docs/caph/01-getting-started/02-quickstart/03-creating-a-workload-cluster.md

Installs upstream Hetzner CSI with working secret ref instead of using unreferenced helm repo.
**TODOs**:

📖 working CSI install instructions

---

controllers/hetznerbaremetalmachine_controller.go
controllers/hetznerbaremetalmachine_controller_test.go
pkg/services/baremetal/baremetal/baremetal.go
pkg/services/baremetal/baremetal/baremetal_test.go
pkg/services/baremetal/host/host.go

:seedling: Increase requeueAfter No Available Host. And trigger Reconcile of hbmm when hbmh is free.

---

api/v1beta1/hcloudmachine_types.go

Remove unused function HCloudMachineSpec()

:seedling: Remove unused function HCloudMachineSpec()

---

README.md

Updating the readme regarding CAPI and supported Kubernetes Versions.
Fixes #
**TODOs**:

:seedling: Updating the Readme

---

pkg/services/hcloud/loadbalancer/loadbalancer.go
pkg/services/hcloud/loadbalancer/loadbalancer_test.go

Avoid panic if hetznercluster.spec.controlPlaneEndpoint is not set
Closes #1600

:seedling: Avoid panic if hetznercluster.spec.controlPlaneEndpoint is not set
