.github/workflows/release.yml, Makefile, docs/developers/releasing.md
Adding informations for releasing
Fixing the release procedure in CI
**TODOs**:
=> :seedling: Adding informations about releasing and fixing CI

README.md, docs/README.md, docs/developers/development.md, docs/developers/tilt.md, docs/topics/quickstart.md
Adds useful information about how to use the hetzner provider.
=> :book: Updating user docs

config/certmanager/certificate.yaml, config/default/manager_webhook_patch.yaml
Fixes the certificate name for the controller aligning to upstream cluster-api naming convention.
=> :bug: fixing certificate name for hetzner controller

templates/cluster-template-hcloud-network.yaml, templates/cluster-template-packer.yaml, templates/cluster-template.yaml
/kind feature           New functionality.
aligns the changes from switching to fedora-35 in the packer image to the cloud-init templates. And adds some basic flags for better testing and enables the csr controller by default.
=> :sparkles: Changes Templates to fedora for easier cgroup v2 handling

main.go, pkg/services/hcloud/placementgroup/placementgroup.go
/kind other
Using cluster name as suffix for placement group names to avoid
colliding naming of placement groups belonging to different clusters in
the same project.
**TODOs**:
=> :seedling: Suffixing placement group names in Hetzner

pkg/services/hcloud/placementgroup/placementgroup.go
Fixes a bug where placement groups are created and deleted in a loop caused by naming a placementgroup with the delimiter.
=> :bug: Fixing placmement group delimiter solves issue which leads to creating and deleting of placementgroups in a loop

api/v1beta1/hcloudmachine_types.go, api/v1beta1/hetznercluster_types.go, api/v1beta1/network_types.go, api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml, templates/cluster-template-hcloud-network.yaml, templates/cluster-template-packer-hcloud-network.yaml, templates/cluster-template-packer-talos.yaml, templates/cluster-template-packer.yaml, templates/cluster-template.yaml
/kind api-change        Adds, removes, or changes an API
Aligning the naming convention to use the plural form of a word if the type is an array.
=> :warning: Aligning naming convention to use the plural form on arrays

api/v1beta1/hetznercluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml
Adding a default if no controlPlaneRegion is set.
=> :seedling: Adding default value fsn1 for controlPlaneRegions

Makefile
Fixing envsubst in Makefile for creating clusters. This bug was introduced by switching from https://github.com/a8m/envsubst to https://github.com/drone/envsubst
=> :bug: Fix makefile envsubst

templates/cluster-template-hcloud-network.yaml, templates/cluster-template.yaml
Adds a resolv.conf for the kubelet to prevent the warning "nameserver limit exceeded"
Fixes #77
=> :bug: Adds a resolv.conf for the kubelet to omit the warning nameserver limit exceeded

pkg/services/hcloud/client/fake/hcloud_client.go
/kind bug
The network that is inputted into CreateServer only contains an ID.
Despite that, we used the pointer to IP range in the CreateServer
function of the fake HCloudClient. This fix switches to the cached
information about networks instead. Nil pointer errors can therefore
be avoided.
**TODOs**:
=> :bug: Fix bug in fake CreateServer

api/v1beta1/hetznercluster_webhook.go, api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml, controllers/controllers_suite_test.go, controllers/hcloudmachine_controller_test.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go, pkg/services/hcloud/network/network.go
/kind cleanup
We have a double naming here: HCloudNetwork.NetworkEnabled instead of Enabled.
**TODOs**:
=> :seedling: Refactor/rename network enabled

controllers/controllers_suite_test.go, controllers/hcloudmachine_controller_test.go, controllers/hetznercluster_controller_test.go
/kind cleanup
Defining HCloudClient centrally in controller_suite_test is more efficient than always using the HCloudClientFactory to create HCloudClients in individual tests.
**TODOs**:
=> :seedling: Define HCloudClient centrally in tests

Makefile, docs/topics/quickstart.md
/kind documentation  
This removes the need of defining a local clusterctl override file for using this provider integration. 
Since clusterctl v1.1.1 we are official supported and could be used by `clusterctl init --infrastructure hetzner`
=> :book: removing clusterctl override as we are now a official provider integration

api/v1beta1/conditions_const.go, pkg/services/hcloud/server/server.go
/kind cleanup
Use conditions instead of error messages to mark control plane as not
ready when no connection to API server could be established.
**TODOs**:
=> :seedling: Use conditions for unready control planes

test/e2e/caph.go, test/e2e/common.go, test/e2e/conformance.go
/kind cleanup
Follow go lint guidelines to not use dot imports in files that do not have suffix ```_test.go```.
**TODOs**:
=> :seedling: Fix linting in test/e2e

go.mod, go.sum
/kind other
Update docker distribution to v2.8.0+incompatible to fix a security
issue raised by dependabot in
https://github.com/syself/cluster-api-provider-hetzner/security/dependabot/1.
**TODOs**:
=> :seedling: Fix security issue with docker distribution

hack/kind-dev.sh
/kind other           
Reverts k8s version of kindest/node from v1.23.4 to v1.23.3, because it's not published yet.
=> :seedling: revert k8s version of kindest/node

api/v1beta1/conditions_const.go, controllers/controllers_suite_test.go, controllers/hcloudmachine_controller.go, controllers/hcloudmachine_controller_test.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go, main.go, pkg/scope/cluster.go, pkg/scope/machine.go, pkg/secrets/error.go, pkg/secrets/label.go, pkg/secrets/secret.go, pkg/services/hcloud/client/fake/hcloud_client.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/helpers/envtest.go
/kind feature
This PR introduces a central way to handle secrets with two functions in pkg folder to acquire and release a secret. This means that from now on the finalizer will be set on secrets that are relevant to certain objects like HetznerCluster. 
Additionally, the cache of the manager is changed, so that it does not include all secrets from the beginning on. Instead, only relevant secrets are included via specific labels which are set. 
As there are some tests failing because the HetznerCluster object is not deleted properly, the tests manually remove the finalizer and delete the secret. This should be investigated in the future. 
**TODOs**:
=> :sparkles: New secret management with caching and finalizers

controllers/hcloudmachine_controller.go, controllers/hetznercluster_controller.go, pkg/scope/cluster.go, pkg/scope/machine.go
/kind bug
After introducing the secret manager, all the places where we work with
secrets need a new way of retrieving secrets, as they are not per se in
the cache anymore. We use the secret manager now everywhere.
**TODOs**:
=> :bug: Fix secrets not handled with secret manager

pkg/scope/cluster.go, pkg/scope/machine.go
/kind bug
With the secret manager we introduced finalizers on secrets. These are
currently set everywhere. However, this introduces some issues as it
requires to remove those finalizers in the delete process again. As we 
don't do this currently, the secrets do not get deleted at all.
Instead, we now do not set the finalizers on bootstrap secret and kubeconfig. 
secret.
**TODOs**:
=> :bug: Remove finalizers from certain secrets

api/v1beta1/hcloudmachine_types.go, api/v1beta1/hetznerbaremetalmachine_types.go, controllers/csr_controller.go, controllers/hetznercluster_controller.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/state_machine.go, pkg/services/hcloud/server/server.go, templates/cluster-template-baremetal.yaml
/kind other
Add a prefix to hostnames to let the cloud controller manager
differentiate bare metal and cloud servers. Update server name in robot
API accordingly.
Small fixes: Add robot credentials into secret for target cluster, add
three host servers in cluster template
**TODOs**:
=> :seedling: Add prefix to hostnames

.gitignore, Makefile, Tiltfile, api/v1beta1/hetznerbaremetalhost_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, controllers/hetznerbaremetalhost_controller.go, controllers/hetznerbaremetalhost_controller_test.go, controllers/hetznerbaremetalmachine_controller_test.go, pkg/scope/baremetalhost.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/baremetal/baremetal_test.go, pkg/services/baremetal/host/action_result.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/state_machine.go, pkg/services/baremetal/host/state_machine_test.go, templates/cluster-template-baremetal-control-planes.yaml, templates/cluster-template-baremetal.yaml, test/helpers/defaults.go
/kind cleanup
As it makes more sense to have a separate host inventory, we remove the
reference to the Hetzner cluster from the host object. This requires
some changes in the states, as we cannot continue with pre-processing,
before a bare metal machine consumes a host. Now all information and
credentials come directly or indirectly from the bare metal machine.
Therefore, the host waits in StateNone until a consumer ref is set.
**TODOs**:
=> :seedling: Remove host logic from individual clusters

controllers/hetznerbaremetalmachine_controller.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go, pkg/services/baremetal/host/state_machine.go, pkg/services/hcloud/server/server.go
/kind bug
The reboot logic in host provisioning had some logical errors. These
errors were quite small and mostly affected cases, where both the user
might have done something wrong, or a Hetzner reboot has not been
triggered. To implement a better fitting solution, the old function
actionEnsureCorrectBoot has been replaced and more logic is now in the
functions calling actionEnsureCorrectBoot before.
**TODOs**:
=> :bug: Fix reboot logic in host provisioning

.github/workflows/golangci-lint.yml, api/v1beta1/conditions_const.go, pkg/scope/machine.go, pkg/services/hcloud/server/server.go, pkg/services/hcloud/server/server_suite_test.go, pkg/services/hcloud/server/server_test.go
/kind feature
In HCloud, servers sometimes get stuck in status off. Even repeatedly
powering them on does not help. This commit introduces a logic that
makes sure, these servers get marked as failed after a certain timeout.
**TODOs**:
=> :sparkles: Handle stuck servers that do not switch on

api/v1beta1/conditions_const.go, controllers/controllers_suite_test.go, controllers/hcloudmachine_controller.go, controllers/hcloudmachine_controller_test.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/network/network.go, pkg/services/hcloud/placementgroup/placementgroup.go, pkg/services/hcloud/server/server.go
/kind feature
We now wait for a fixed time if a rate limit error occurs while
reconciling a machine or the cluster object. The logic relies on
conditions, where RateLimitExceeded is set to true. The machine and
cluster controller requeue reconciling at the beginning for a fixed time
period, until the waiting time is over and the reconciling can start
again.
**TODOs**:
=> :sparkles: Handle rate limit errors in HCloud

api/v1beta1/hetznercluster_types.go, api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml
/kind bug
Load balancer specs are required in cluster spec - remove the optional tag of kubebuilder.
**TODOs**:
=> :seedling: Make lb spec required

docs/reference/README.md, docs/reference/hcloud-machine-template.md, docs/reference/hetzner-bare-metal-host.md, docs/reference/hetzner-bare-metal-machine-template.md, docs/reference/hetzner-cluster.md, docs/topics/managing-ssh-keys.md
Add a reference for all important API objects in the /docs/reference
folder.
**TODOs**:
=> :book: Add object references in docs

docs/developers/tilt.md, test/e2e/capi_e2e_clusterctl_upgrade_test.go, test/e2e/clusterctl_upgrade.go, test/e2e/config/hetzner-ci.yaml, test/e2e/config/hetzner.yaml
Adds an e2e test to test against an older infrastructure provider version to ensure compatibility with the previous version of the caph controller.
=> :seedling: Adding e2e test to test upgrade from a previous caph version

test/e2e/clusterctl_upgrade.go
Adds a boilerplate header to e2e test
=> :seedling: Fixing boilerplate in e2e test clusterctl upgrade

Makefile, test/e2e/data/kubetest/conformance.yaml
/kind failing-test   
* Fixes conformance test. Skips hostpath test since cilium doesn't support it. https://github.com/cilium/cilium/issues/14287
* Workload upgrade should run in parallel
=> :seedling: Fixing conformance test and run workload upgrade in parallel

.github/actions/e2e/action.yaml
/kind other        
Follow-up for caph upgrade e2e test. Bumps to v1.0.0-alpha.19
=> :seedling: Bump latest released version for e2e

docs/reference/hetzner-bare-metal-host.md, docs/reference/hetzner-bare-metal-machine-template.md, docs/topics/quickstart.md
Adds more info about the HetznerBareMetalHost object to make it clearer how to use Hetzner bare metal servers with the cluster-api. Also adds some more info about the baremetal deployment to the quickstart.md.
Fixes #209
-
**TODOs**:
=> :book: Documentation update (baremetalhost)

README.md, docs/developers/tilt.md
/kind documentation  
The next version of caph will support the new v1.2.x capi version
=> :book: adding capi v1.2.x support

pkg/services/hcloud/server/server.go
/kind bug
In one of the last PRs we added support for Hetzner's new feature of
disabling IPv4 and IPv6 addresses. This required to prevent servers from
being added to load balancer in case they only have IPv6 addresses - as
no IPv6 addresses can be added to a Hetzner load balancer. This only
applies to public network though. This is why we also need to add
servers in case that private networks are there - independent whether
there is a public IPv4 or not.
**TODOs**:
=> :bug: Fix add server to lb with only private IP

api/v1beta1/conditions_const.go, controllers/hcloudmachine_controller_test.go, controllers/hetznerbaremetalmachine_controller_test.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/hcloud/server/server.go
/kind feature
It is not very clear, without looking at logs, that a machine is
currently waiting for its bootstrap data. In order to facilitate the
operator's job, we include this as a condition into the machine's
status.
**TODOs**:
=> :sparkles: Add condition for bootstrap ready

.github/workflows/pr-unit-test.yml, .github/workflows/pr-verify-code.yml, .github/workflows/release.yml, .golangci.yaml, Dockerfile, Makefile, go.mod, hack/tools/go.mod
/kind other
Latest Go version, needed for upcoming CAPI 1.25 release
**TODOs**:
=> :sparkles: Bump Go to 1.19

.github/workflows/pr-e2e.yaml, test/e2e/feature_test.go
/kind cleanup          
* disables e2e loadbalancer disabled test, because we do not support setting a host in the CI
=> :seedling: clean-up of e2e tests

docs/reference/hcloud-machine-template.md, pkg/services/hcloud/server/server.go
/kind bug
Currently, the user can only enable/disable IPv4 and IPv6 if there is no private network. However, since the enabling/disabling is independent of the public/private net, we remove this if clause.
To make sure that users don't disable the IPv4 if there is no private net, we always enable it in that case. This is necessary for Hetzner load balancers, as they can only work with IPv4 of HCloud servers.
Fixes #312
**TODOs**:
=> :bug: Fix enabling IP address logic for HCloud

controllers/hetznercluster_controller.go
Don't mark the cluster as ready when the LB is enabled but has no IP address yet.
/kind bug
Currently, if the LB is enabled but doesn't have an IP address yet, but an (incomplete) controlPlaneEndpoint is configured in the HetznerCluster resource, the infrastructure is marked as ready leading to wrong endpoint data being used by the bootstrap provider.
Fixes #454
**TODOs**:
=> 🐛 Wait for LoadBalancer IP

templates/cluster-templates/bases/hetznerbaremetal-mt-control-plane-ubuntu.yaml, templates/cluster-templates/bases/hetznerbaremetal-mt-md-1-ubuntu.yaml
/kind bug
Cloud-init generates another own DHCP entry for netplan on baremetal machines despite existing static configuration. This leads to problems and duplicate network configuration.
This fix disables cloud-inits network config through a custom config-file created before cloud-init runs.
**Which issue(s) this PR fixes:**:
Fixes #457 
**TODOs**:
=> :bug: Fix baremetal networking due to erroneous netplan-config / cloud-init

api/v1beta1/hcloudmachinetemplate_webhook.go, api/v1beta1/hetznerbaremetalmachinetemplate_webhook.go, api/v1beta1/hetznercluster_types.go, api/v1beta1/hetznercluster_webhook.go, api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml, config/webhook/manifests.yaml, main.go, templates/cluster-templates/cluster-class-topology-example.yaml, templates/cluster-templates/cluster-class.yaml, test/helpers/envtest.go
/feature
Enable SSA apply for HCloudMachineTemplate and HetznerBareMetalMachineTemplate by using admission.CustomValidator. This is the foundation to efficiently use the ClusterClass feature of CAPI.
**TODOs**:
=> :sparkles: Enable SSA apply for hcloud and bare metal templates

controllers/hcloudmachinetemplate_controller.go
/kind bug
In HCloudMachineTemplate controller there is a nil pointer error due to a missing InfrastructureRef of the Cluster object when using ClusterClass. A check for missing InfrastructureRef and reconciling again solves this.
**TODOs**:
=> :bug: Add check for empty infra ref of cluster

pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go
/kind bug
In actionEnsureProvisioned we check whether cloud init actually ran successfully: Sometimes it happens that it shows success, but has a SIGTERM in the logs.
However, if we change ssh ports in cloud init, then we have to call the new port after cloud init finished. If this works, we can already conclude that cloud init did something right. This is enough reason for us to assume that everything went well.
If this is a wrong assumption, we can include in the future an additional if statement that makes ssh statements to both ports to check the current cloud init status.
**TODOs**:
=> :bug: Fix ssh call to wrong port in actionEnsureProvisioned

.github/actions/manager-image/action.yaml, .github/workflows/build.yml, .github/workflows/pr-e2e.yaml, .github/workflows/schedule-cache-cleaner-caph-image.yml
Adds a cache to the image build. Every time a PR is opened, the e2e triggers an image build of caph. We could speed up this process by using the cache. The cache is only updated during a nightly build in the main branch. Since we expect the changes in a PR to be minor, it makes sense to use the main branch cache. Release builds will not use a cache.  
Since using a Golang cache in Github actions is not natively supported, we use a fake Dockerfile to import and export the cache to the local Docker cache, and use Buildkit's mount directives.
Fixes #
_Please …
=> :seedling: adding cache to image build

pkg/services/hcloud/network/network.go
Right now the Subnet is created with the same CIDR as the whole network. This breaks native routing inside the Network, as the full range of the network is blocked by the Subnet. There is already a field for the subnet that should be used instead: `SubnetCIDRBlock`.
Fixes #612
=> 🐛 Subnet does not use the specified CIDR

api/v1beta1/hcloudmachine_types.go, api/v1beta1/hetznerbaremetalmachine_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml, controllers/csr_controller.go, pkg/csr/csr.go, pkg/csr/csr_test.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/baremetal/baremetal_test.go, pkg/services/hcloud/server/server.go, pkg/services/hcloud/server/server_suite_test.go
Change corev1.NodeAddress to clusterv1.MachineAddress.
Related Slack conversation: https://kubernetes.slack.com/archives/C8TSNPY4T/p1677234946342759
According to the cluster-api documentation, the Status should be a MachineAdress (api from cluster-api)
https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine.html#optional-status-fields-1
**TODOs**:
=> :seedling: corev1.NodeAddress -> clusterv1.MachineAddress

Makefile
There was a typo in the Makefile, so that the version of golangci-lint was not updated.
=> :bug: fixed: install matching golangci version

pkg/services/baremetal/remediation/remediation.go
We have to initialize a nil map. Otherwise, we get a "panic: assignment to nil map" error. The bug has been discovered in https://github.com/syself/cluster-api-provider-hetzner/issues/657. 
**TODOs**:
=> :bug: Init host annotation map in remediation controller

Makefile, api/v1beta1/hetznerbaremetalhost_types.go, api/v1beta1/zz_generated.deepcopy.go, controllers/hetznerbaremetalmachine_controller_test.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/baremetal/baremetal_test.go
Currently, we cannot distinguish cases where maintenanceMode is set and false from those once where it is not set. This creates some issues with e.g. ArgoCD. Therefore, we use a pointer to clearly distinguish the cases. If not set, the maintenanceMode is omitted in the Kubernetes object.
**TODOs**:
=> :seedling: Make host.MaintenanceMode a pointer

Makefile, api/v1beta1/hetznerbaremetalhost_types.go, api/v1beta1/hetznerbaremetalhost_types_test.go, api/v1beta1/hetznerbaremetalmachine_types.go, api/v1beta1/hetznerbaremetalmachine_types_test.go, api/v1beta1/hetznerbaremetalmachine_webhook.go, api/v1beta1/suite_test.go, controllers/hetznerbaremetalhost_controller.go, pkg/scope/baremetalhost.go, pkg/scope/baremetalmachine.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_suite_test.go, pkg/services/baremetal/host/host_test.go, pkg/services/baremetal/host/state_machine.go
Moving functions that can be defined on an API object to the api folder. Writing tests for it.
**TODOs**:
=> :seedling: Move utility functions from host pkg to api

templates/node-image/1.25.2-ubuntu-22-04-containerd/scripts/cilium-requirements.sh
The added configuration is required on Ubuntu 22.04 according to the [cilium-docs].
In my personal cluster, not setting these values would cause the Host networking to break after "[unattended-upgrades]" were executed and core system services restarted. This happened roughly once per day and had the potential to take down the whole cluster.
[cilium-docs]: https://docs.cilium.io/en/v1.13/operations/system_requirements/#systemd-based-distributions
[unattended-upgrades]: https://help.ubuntu.com/community/AutomaticSecurityUpdates
/
**TODOs**:
=> 🐛 Missing cilium networkd configuration on Ubuntu 22.04

templates/cluster-templates/hcloud-talos-packer/kustomization.yaml
/kind bug
KubeAdm was included by mistake in Talos build
I don't know how to test it, please check.
=> 🐛 fix: talos md

.github/renovate/golang.json5, .golangci.yaml, go.mod, hack/tools/go.mod, images/caph/Dockerfile
This PR upgrades Go to 1.20. This is needed to use `errors.Join()` or multiple `%w` entries in `fmt.Errorf()`.
=> :seedling: Upgrade Go to 1.20.2

controllers/hetznerbaremetalhost_controller.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_suite_test.go, pkg/services/baremetal/host/host_test.go, pkg/services/baremetal/host/state_machine.go, pkg/services/baremetal/remediation/remediation.go, pkg/services/hcloud/server/server.go
github.com/pkg/errors is included in the standard library for some time now. We should use the standard lib everywhere
**TODOs**:
=> :seedling: Use errors in host package

test/e2e/config/hetzner-ci.yaml, test/e2e/config/hetzner.yaml
The timeouts were too high in most of the cases. To make it more understandable, comments are describing what the interval is meant to be used for. Most intervals are not used at all.
**TODOs**:
=> :seedling: Update timeouts for E2E tests

controllers/hcloudmachinetemplate_controller.go, main.go
Enable concurrent reconciles for the cluster and machine controllers. Default is always 1, i.e. no concurrency.
**TODOs**:
=> :sparkles: Enable concurrent reconciles

pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go
There is currently a case where a bare metal server cannot start due to a wrong ssh key, but the user is not notified except for log messages.
Now an event is published and the host machine sets a fatal error, so that it is obvious to the user that something is wrong.
The use case is when the user uses an ssh key for bare metal which has been already uploaded to Hetzner robot under a different name. As the keys are compared via name, the controller does not figure out that the key exists in reality and uploads it again. This is when Hetzner Robot returns an error.
**TODOs**:
=> :sparkles: Notify user when robot ssh key already exists

api/v1beta1/hetznerbaremetalmachine_types.go, api/v1beta1/hetznerbaremetalmachine_types_test.go, controllers/hetznerbaremetalhost_controller.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go, go.mod, pkg/scope/baremetalhost.go, pkg/scope/baremetalmachine.go, pkg/scope/baremetalremediation.go, pkg/scope/cluster.go, pkg/scope/hcloudmachinetemplate.go, pkg/scope/hcloudremediation.go, pkg/scope/machine.go, pkg/secrets/secret.go, pkg/services/baremetal/client/ssh/ssh_client.go, pkg/services/baremetal/remediation/remediation.go, pkg/services/hcloud/client/fake/hcloud_client.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/machinetemplate/machinetemplate.go, pkg/services/hcloud/network/network.go, pkg/services/hcloud/placementgroup/placementgroup.go, pkg/utils/utils.go, test/e2e/log_collector.go, test/helpers/mod.go
Replacing the outdated pkg/errors library with the standard Go library which contains everything from the pkg/errors library.
**TODOs**:
=> :seedling: Replace pkg/errors with std lib errors

test/e2e/Makefile, test/e2e/common.go
fix nil-pointer exception, if the e2e test failed.
avoid warnings of the ginko command
don't rerun flaky tests.
=> :seedling: Fewer warnings in e2e test

api/v1beta1/conditions_const.go, controllers/hetznercluster_controller.go
We now track the status of the target cluster (workload cluster) through conditions in HetznerCluster object.
When a cluster starts, there are multiple errors that occur temporarily, but are expected. However, they litter the log files and make it harder to debug a cluster, especially for users who are not so familiar with the code.
To reduce the error messages, we use conditions that indicate that a certain step cannot be done yet. If a rare case happens when the cluster is stuck forever in a certain state which is related to errors that we ignore at the beginning, then the user can use the conditions in HetznerCluster to find out what happens.
**TODOs**:
=> :sparkles: Track target cluster status through conditions 

test/e2e/config/hetzner-ci.yaml, test/e2e/config/hetzner.yaml
Our timeout for control planes is currently 15 minutes. This is not enough for bare metal, as it is used separately for a) the first control plane (which needs max 15m) and b) all the rest of the control planes (which need more time from the point where the first control plane is ready).
**TODOs**:
=> :seedling: Increase e2e timeout for control planes

api/v1beta1/conditions_const.go, api/v1beta1/hetznerbaremetalhost_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml, controllers/hetznerbaremetalhost_controller.go, controllers/hetznerbaremetalhost_controller_test.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/state_machine.go
Adding conditions in case that something is wrong with secrets or credentials which the user has to specify. There are secrets for Hetzner robot and for the SSH keys used to provision the bare metal servers.
Removing the error message of spec.status from printcolumns, as it is used only internally for the controller to manage the provisioning process.
**TODOs**:
=> :sparkles: Add conditions to HetznerBareMetalHost

config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudremediations.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudremediationtemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediations.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalremediationtemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml
In the update to controller-gen v0.11.3 the CRDs where not updated accordingly.
**TODOs**:
=> :bug: Update CRDs after update of controller-gen

test/e2e/data/shared/v1beta1/metadata.yaml
The metadata used for e2e tests and clusterctl has to be updated as well to CAPI 1.4
**TODOs**:
=> :bug: Update metadata for e2e tests and CAPI 1.4

controllers/hcloudmachine_controller.go, controllers/hetznerbaremetalmachine_controller.go, controllers/hetznercluster_controller.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/server/server.go
When a HCloud server is locked, this is because the API is doing something for a short time where no other API request for that server can go through - namely right after a server is created. We ignore these errors in the future and just trigger another reconcilement.
Additionally, some unused log statements are removed.
**TODOs**:
=> :seedling: Improve error handling for locked servers

Makefile
fix `kubectl patch` in delete-workload-cluster
Up to now the command always failed.
`paused` is a boolean:
```
❯ k explain cluster.spec.paused
KIND:     Cluster
VERSION:  cluster.x-k8s.io/v1beta1
FIELD:    paused <boolean>
DESCRIPTION:
Paused can be used to prevent controllers from processing the Cluster and
all its associated objects.
```
=> :seedling: fix `kubectl patch` in delete-workload-cluster

controllers/hetznercluster_controller.go
Don't use magic string "kube-system".
make code a bit cleaner by avoiding the magic string "kube-system".
=> :seedling: use metav1.NamespaceSystem

.golangci.yaml
added linter loggercheck
**Which issue(s) this PR fixes** 
Avoid panic at runtime, if you accidentely use uneven key-value pairs for logging.
> panic: odd number of arguments passed as key-value pairs for logging
=> :seedling: added linter loggercheck

Makefile
Last PR introduced an bug.
BUILDER_IMAGE_VERSION was empty.
=> :bug: fix BUILDER_IMAGE_VERSION

pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/client/ssh/ssh_client.go
The bare metal servers are supposed to be resetted when a HetznerBareMetalMachine object is deleted. At the moment, there are two problems. First, the SSH secret reference was deleted before it was used and second the SSH command didn't work.
TODO: Update SSH command
**TODOs**:
Current failure:
"[preflight] Running pre-flight checks\n[reset] No etcd config found. Assuming external etcd\n[reset] Please, manually reset etcd to prevent further issues\n[reset] Stopping the kubelet service\n[reset] Unmounting mounted directories in "/var/lib/kubelet\"\n[reset] Deleting contents of directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]\n[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf …
=> :bug: Fix resetting bm servers

.envrc.sample, Makefile, Tiltfile, controllers/hcloudmachinetemplate_controller.go, controllers/hetznerbaremetalhost_controller.go, controllers/hetznercluster_controller.go, hack/ci-e2e-delete-token.sh, hack/get-kubeconfig-of-workload-cluster.sh, hack/output-for-watch.sh, pkg/scope/baremetalremediation.go, pkg/services/baremetal/client/robot/credentials.go, pkg/services/baremetal/remediation/remediation.go, templates/cluster-templates/bases/hcloud-hetznerCluster-network.yaml, templates/cluster-templates/bases/hcloud-hetznerCluster.yaml
* This PR extends the .envrc.sample file and adds a check for env vars in the makefile targets "create-workload-....".
* Fix for hetzner-ccm requiring "robot-user" and "robot-password" to be in the secret called "hetzner" in the wl-cluster.
* Fix for BM remediation (PatchHelper was used incorrectly).
=> :seedling: .envrc.sample, fix hetzner-ccm, fix BM remediation.

api/v1beta1/hcloudmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml
https://www.hetzner.com/news/new-dedicated-vcpu-cloud-server
Hetzner has recently introduced new AMD EPYC instances. This makes them usable with CAPH.
=> 🌱 Update HCloud instance types

templates/cluster-templates/bases/hcloud-kcp-ubuntu.yaml
ARM support was added with https://github.com/syself/cluster-api-provider-hetzner/pull/766, but the ARCH variable was missing in the KubeadmControlPlane yaml file.
Fixes #865.
=> :bug: Add missing ARCH variable to the Ubuntu KubeadmControlPlane

api/v1beta1/conditions_const.go, controllers/hetznercluster_controller_test.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/network/network.go
There are two conditions that are automatically set on false if there is no network. This can be misleading as there is no network intentionally. This commit changes the logic so that conditions are only set on false if there is a (temporary) problem
**TODOs**:
=> :seedling: Do not mark conditions false if no network exists

controllers/hcloudmachinetemplate_controller.go, controllers/hcloudmachinetemplate_controller_test.go
remove constant logging
> HCloudMachineTemplate is missing cluster label or cluster does not exist
```
❯ tilt logs --port 10351  | grep 'HCloudMachineTemplate is missing cluster label' | wc -l 
469 (in 38 minutes, with --sync-period=3s)
```
=> :seedling: fix constant log "... is missing cluster label"

api/v1beta1/conditions_const.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go
We took the naming of the aws provider:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/cdbaf654af78585d507ba333c10ce3e678944616/api/v1beta2/conditions_consts.go#L116
=> :seedling: rename Condition of loadbalancer

api/v1beta1/hcloudmachine_types.go, api/v1beta1/hcloudmachinetemplate_types.go, api/v1beta1/hcloudremediation_types.go, api/v1beta1/hetznerbaremetalmachine_types.go, api/v1beta1/hetznercluster_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudremediations.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, controllers/hetznercluster_controller.go, pkg/scope/baremetalmachine.go, pkg/scope/cluster.go, pkg/scope/hcloudmachinetemplate.go, pkg/scope/hcloudremediation.go, pkg/scope/machine.go
use SetSummary, extend printcolumns.
Related: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20200506-conditions.md#data-model-changes
CRDs of CAPH:
```
❯ find config/crd/bases/ -name '*.yaml' | xargs grep -l 'kind: CustomRe' | xargs grep -hoP 'plural: \K\S+'
```
* hetznerclusters: changed
* hcloudmachines: changed
* hcloudremediationtemplates: changed
* hcloudremediations: changed
* hetznerbaremetalhosts:  not changed, has not defer up to now. Unclear where to put SetSummary()
* hetznerbaremetalmachines: changed
* hetznerbaremetalmachinetemplates: not changed, has no status
* hcloudmachinetemplates: changed
* hetznerclustertemplates: not changed, has no status
* hetznerbaremetalremediationtemplates: not changed, not …
=> :seedling: use SetSummary, extend printcolumns.

controllers/hcloudmachine_controller.go, controllers/hcloudmachinetemplate_controller.go, controllers/hcloudremediation_controller.go, controllers/hetznerbaremetalmachine_controller.go, controllers/hetznercluster_controller.go
Every modification, which gets done before the patchHelper gets created, will not be detected as change.
We need to set MarkTrue() after the patchHelper was created.
=> :bug: Fix conditions getting ok again.

api/v1beta1/conditions_const.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go, pkg/services/hcloud/client/fake/hcloud_client.go, pkg/services/hcloud/client/fake/hcloud_client_test.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/loadbalancer/loadbalancer_test.go
Re-using existing load balancer if name of load balancer is set in spec
**TODOs**:
=> :sparkles: Reuse existing load balancer

api/v1beta1/conditions_const.go, controllers/controllers_suite_test.go, controllers/hcloudmachine_controller_test.go, controllers/hetznerbaremetalmachine_controller.go, controllers/hetznerbaremetalmachine_controller_test.go, controllers/hetznercluster_controller_test.go, pkg/scope/baremetalmachine.go, pkg/scope/cluster.go, pkg/scope/machine.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/server/server.go, pkg/services/hcloud/server/server_test.go
Refactoring conditions of HetznerBareMetalMachine and HCloudMachine to make them more readable and more expressive.
Actively deleting deprecated conditions from objects
**TODOs**:
=> :seedling: Refactor conditions of provider machine objects

api/v1beta1/conditions_const.go, controllers/controllers_suite_test.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go, pkg/services/baremetal/host/utils.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/network/network.go, pkg/services/hcloud/placementgroup/placementgroup.go
Refactoring conditions to improve naming and set more precise conditions.
Actively remove deprecated conditions from objects so that they are not stuck on existing objects from older versions of the operator.
**TODOs**:
=> :seedling: Refactor conditions of HetznerCluster

controllers/controllers_suite_test.go, controllers/hcloudmachine_controller_test.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go
Refactoring tests of hcloud controller to better re-use objects, add useful comments, remove unnecessary code and improve naming
**TODOs**:
=> :seedling: Refactor hcloudcontroller tests

.github/actions/e2e/action.yaml, .github/workflows/e2e-basic-baremetal.yaml, .github/workflows/e2e-basic-packer.yaml, .github/workflows/e2e-basic.yaml, .github/workflows/e2e-feature-baremetal.yaml, .github/workflows/e2e-feature.yaml, .github/workflows/e2e-periodic.yaml, .github/workflows/e2e-upgrade-caph.yaml, .github/workflows/e2e-upgrade-kubernetes.yaml, .github/workflows/pr-e2e.yaml, hack/ci-e2e-delete-token.sh, hack/ci-e2e-get-token.sh
TTS is being replaced by TPS. TPS now uses (primarily) GitHub Actions OIDC tokens and has a reusable GitHub Action to get the token.
This does require additional permissions for the jobs that need to talk to TPS, to generate the OIDC tokens.
Right now, there is no way (and no need) to cleanup these tokens, they will be deleted at the end of their configured lifetime.
TPS creates temporary projects instead of tokens for one project.
You can remove the `TTS_TOKEN` from the repository settings once you have merged & validated this PR.
=> :seedling: replace deprecated TTS for getting temp hetzner cloud tokens

pkg/services/hcloud/placementgroup/placementgroup.go
THe current `placementgroup.Service` lists the placement groups twice in `Reconcile()`. Once at the beginning, and another time at the end to get an up-to-date view for the status update.
The second request is only necessary in case the controller made any updates to the list (create, delete), but this happens rarely. 
In my personal cluster, this has reduced the rate of requests to `GET /v1/placementgroups` from 0.2req/s to 0.12req/s.
Fixes #
**TODOs**:
=> 🌱 make less api calls on up-to-date placement groups

api/v1beta1/conditions_const.go, pkg/services/hcloud/server/server.go
Adding conditions in case of ambiguous images or in case no image is found for a hcloud server on creation
**TODOs**:
=> :seedling: Set condition in case of errors with  hcloud images

controllers/hetznerbaremetalhost_controller.go, controllers/hetznerbaremetalmachine_controller.go, go.mod, go.sum, main.go, pkg/services/baremetal/client/robot/robot_client.go, pkg/services/baremetal/host/host.go, vendor/github.com/syself/hrobot-go/README.md, vendor/github.com/syself/hrobot-go/client.go, vendor/modules.txt
Add logging to hetzner robot client, so that we have a better understanding why the rate-limit get reached.
=> :sparkles: Add logging to hetzner robot API client.

api/v1beta1/conditions_const.go, api/v1beta1/hetznerbaremetalhost_types.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go
Introducing the permanent error on host objects to leverage the fact that there are some errors that occur during provisioning of a host that cannot be fixed, namely that the Hetzner robot device does not exist with that respective serverID, or that there is no rescue mode for the server.
In cases where there are errors that cannot be recovered without provisioning another time, the FatalError is used which leads to a FailureMessage on the bm machine.
In cases where there is a configuration problem or a failure of the scripts that the user provided, there is an error that stays on the host as well as a condition that shows a user-facing error, e.g. that there is no cloud-init installed, or that an ssh key already exists under a different name and …
=> :sparkles: Introducing permanent error for host objects

controllers/hetznerbaremetalmachine_controller_test.go, controllers/hetznercluster_controller_test.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/util/utils.go
The feature of taking over existing load balancers did not pay attention to the kubeapi service which is not added to the load balancer. This is due to the fact that this was done in the creation process only.
This commit adds it to the reconcilement of the extraServices so that it gets added to an existing load balancer as well.
**TODOs**:
=> :bug: Add kubeapi service to existing load balancer

api/v1beta1/conditions_const.go, controllers/hetznerbaremetalhost_controller.go, pkg/services/baremetal/host/action_result.go, pkg/services/baremetal/host/host.go
There were multiple issues with the return results of host objects:
- SaveHostAndReturn has overwritten the actual value in the defer statement
- We requeued after Updates of hosts always because we didn't use reflect.DeepEqual to compare pointers
- We requeuedAfter a certain time period for permanent errors which does not make sense. This is why a new actionPermanent is introduced that does not have any requeue
**TODOs**:
=> :bug: Fix return result for bm hosts

pkg/services/hcloud/client/client.go
Setting the ["Application"](https://pkg.go.dev/github.com/hetznercloud/hcloud-go/hcloud#WithApplication) in the hcloud-go client adds that information to the "User-Agent" of all outgoing http requests to the Hetzner Cloud API. This data helps Hetzner Cloud find potentially misbehaving API clients.
I saw that you have a [script to include version information](https://github.com/syself/cluster-api-provider-hetzner/blob/271d7452c427b11217910e281e5150888dac2096/hack/version.sh#L72-L93) in the built binaries, but I could not find the referenced go package, and left the version parameter empty.
/
**TODOs**:
=> 🌱 Set Application Name in hcloud-go client

api/v1beta1/conditions_const.go, controllers/hetznercluster_controller_test.go, pkg/services/hcloud/client/fake/hcloud_client.go, pkg/services/hcloud/loadbalancer/loadbalancer.go
When a cluster is deleted, the load balancer is usually deleted. However, if the user specified the name of an existing load balancer in the spec, the expectated behavior would be that the load balancer of the user is not deleted when a cluster is deleted.
This commit implements that behavior and also removes the cluster label from the load balancer.
It also improves the conditions and events for load balancer deletion.
A problem with pointers is fixed which caused an issue in the fake hcloud client, where we implicitly updated the load balancers with the pointer, instead of using the actual API call.
In order to fix this, the API fake behavior is fixed and labels are also updated, according to the behavior of the actual hcloud-go client
**TODOs**:
=> :bug: Remove cluster label from existing lb on delete

.github/actions/e2e/action.yaml, test/e2e/config/hetzner-ci.yaml, test/e2e/config/hetzner.yaml
This updates the latest caph version to v1.0.0-beta.22 and updates capi to v1.5.2
Fixes #
**TODOs**:
=> :seedling: update caph latest version and capi

pkg/services/hcloud/network/network.go
The list of servers returned by the API is not consistently sorted. As the IDs from this list are written into
HetznerCluster.Status.NetworkStatus.AttachedServers in this random order, this causes uncesseary patches to the HetznerCluster object.
By sorting the IDs before writing, only actual changes causes the object to be patched.
As other controllers have a watch on HetznerCluster, this reduces the general amount of reconciles happening in CAPH.
Related to #926
Closes #926
This depends on #905, as Go 1.21 introduce a nice new way to sort `int64` slices. …
=> 🌱 reduce reconciles by sorting hetznerCluster.status.networkStatus.attachedServers

api/v1beta1/conditions_const.go, controllers/hetznerbaremetalhost_controller.go, controllers/hetznercluster_controller.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/server/server.go
There are multiple places where the controller requeues by setting the parameter explicitly or by returning an error, where it is not necessary or even bad because it leads to a loop where the controller might run in rate limits of hcloud or hrobot APIs.
This commit introduces multiple fixes:
- if something is not correct while creating hcloud servers that needs user intervention, the controller requeues after 5 minutes and does not return an error.
- in other places where there is a requeue that is not needed it is removed
- when provisioning the host fails and there is a timeout reached due to which the controller does not expect the server to provision successfully, there is no an error set on the host as well as an exponential backoff time for …
=> :bug: Fix requeue on error

pkg/services/baremetal/client/ssh/ssh_client.go, pkg/services/baremetal/host/host.go
Up to now deprovisioning of bare-metal servers failed. The reason was because there was output on stdout.
We fixed that and improved the deprovisioning (delete all pods, stop and disable kubelet via systemclt, remove /etc/kubernetes).
=> :seedling: handle deprovision of bare metal.

api/v1beta1/hcloudmachine_types.go, api/v1beta1/hetznerbaremetalhost_types.go, api/v1beta1/hetznerbaremetalmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalmachines.yaml
Align printcolumns of several CRDs.
Current result:
```
❯ k get hcloudmachine
NAME                               CLUSTER        MACHINE                                    STATE     AGE     REASON   MESSAGE
caph-guettli-control-plane-24hhs   caph-guettli   caph-guettli-control-plane-t9w8q           running   6h45m            
caph-guettli-md-0-8xtnv            caph-guettli   caph-guettli-md-0-54bf746bc6xwzz5s-mk7rj   running   6h46m            
```
```
❯ k get hetznerbaremetalmachine ; k get hetznerbaremetalhosts
NAME                      CLUSTER        HOST                  MACHINE                                   PHASE          AGE   REASON              MESSAGE
caph-guettli-md-1-7d6rm   caph-guettli   default/test-bm-gpu …
```
=> :sparkles: printcolumns alignement.

pkg/services/baremetal/client/robot/robot_client.go
Showing robot api calls only on debug level
**TODOs**:
=> :seedling: Show api calls only in debug mode

api/v1beta1/conditions_const.go, controllers/hetznercluster_controller.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/host/host.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/network/network.go, pkg/services/hcloud/server/server.go
Renaming deprecated conditions to show in the Go code easily that they should not be used anymore
**TODOs**:
=> :seedling: Rename deprecated conditions

api/v1beta1/hcloudmachine_types.go, api/v1beta1/hetznerbaremetalhost_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerbaremetalhosts.yaml
Changing HetznerBareMetalHost printcolumn state to phase to align with the printcolumns of the other objects
**TODOs**:
=> :seedling: Aligning printcolumn phase of all objects

Tiltfile, config/manager/manager.yaml, go.mod, main.go, pkg/services/baremetal/client/robot/robot_client.go
Fix logger of robot api and switch to pflag package
**TODOs**:
=> :bug: Fix robot log and switch to pflag

Tiltfile, api/v1beta1/conditions_const.go, controllers/hcloudmachinetemplate_controller.go, controllers/hetznercluster_controller.go
Improving the startup of the target (workload) cluster manager to avoid unnecessary and temporary errors that come while the first control plane is still provisioning.
This is done by an additional check whether the control plane is available already.
Furthermore, this commit introduces a new condition so that the Hetzner secret that is stored in the target cluster reconciles with an own condition.
**TODOs**:
=> :seedling: Improve startup of target cluster manager

pkg/services/baremetal/host/host.go
Delete provisioning condition from HetznerBareMetalHost in the deprovisioning step so that it does not show anymore after the host is successfully deprovisioned.
**TODOs**:
=> :bug: Delete provision condition after deprovisioning

.github/actions/setup-go/action.yaml
`set-output` syntax was deprecated few months back in GitHub and this
commit updates the workflow manifest with the current supported syntax.
Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warnings: https://github.com/syself/cluster-api-provider-hetzner/actions/runs/6362488278
Signed-off-by: Anurag <kranurag7+81210977@users.noreply.github.com>
Fixes #
**TODOs**:
=> 🌱 update output syntax in go workflow

controllers/hcloudmachine_controller_test.go, pkg/services/hcloud/client/fake/hcloud_client.go, pkg/services/hcloud/client/fake/hcloud_client_test.go
=> 🌱 test for server image list condition

controllers/controllers_suite_test.go, controllers/hcloudremediation_controller.go, controllers/hcloudremediation_controller_test.go, controllers/hetznerbaremetalremediation_controller.go, controllers/hetznerbaremetalremediation_controller_test.go, pkg/services/baremetal/remediation/remediation.go
Fixes # https://github.com/syself/open-source/issues/76
**TODOs**:
=> ✨ Add tests for hcloud remediation and hetzner baremetal remediation controller

pkg/services/baremetal/remediation/remediation.go, pkg/services/hcloud/remediation/remediation.go
=> 🌱 Refactor events for remediation controllers

pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/state_machine.go
There has been a time lag in the condition that shows the provisioning status of the HetznerBareMetalHost. It was only updated after a new reconcilement has started, not during the reconcilement where the state actually changed.
This commit places the update of the condition to the start of the respective functions to ensure it is up to date.
**TODOs**:
=> :bug: Fix provision condition time lag

.github/workflows/schedule-cache-cleaner-caph-image.yml, .github/workflows/schedule-link-checker.yml, .github/workflows/schedule-scan-image.yml
this commit enables few workflows to run only on upstream repo and disables it on forked repos.
fixes #554
Fixes #554 
**TODOs**:
=> 🌱 update workflows to run only on upstream repo

controllers/hetznercluster_controller.go
Ensure that target secret contains only robot credentials if they are not empty.
Fixes #1007
**TODOs**:
=> :bug: Ensure secret contains non-empty creds

controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go
The following PR addresses the issue #977, and aims to add the function SetControlPlaneEndpoint() and unit tests for it. 
Fixes #977 
No it does not
**TODOs**:
=> :seedling: Add SetControlPlaneEndpoint function

Makefile
this commit add new make target `make generate-hcloud-token` and bumps the version of some components in the Makefile.
Fixes #
**TODOs**:
=> 🌱 Add make generate-hcloud-token and bump versions

pkg/services/baremetal/host/host.go
Adding an event to show that the provisioning process has been completed. This is important to find out based on events where an issue happens. Even if it is successfully provisioned, it might not be added to the cluster, as the CCM does some work after CAPH. To know more about the state, this event will be helpful.
**TODOs**:
=> :seedling: Add event if host is provisioned

api/v1beta1/conditions_const.go, pkg/services/baremetal/host/host.go
Add conditions to make validation of rootDeviceHints in the bare metal provisioning process easily visible to the user.
small other change: remove second call to obtain storage devices, as the information is already specified in the object itself.
Fixes #1044
**TODOs**:
=> :sparkles: Add conditions for rootDeviceHint validation

api/v1beta1/conditions_const.go, controllers/hetznercluster_controller.go, pkg/services/baremetal/host/host.go, pkg/services/hcloud/machinetemplate/machinetemplate.go, pkg/services/hcloud/server/server.go
Removing deprecated rate limit conditions of all objects.
Fixes #1026
**TODOs**:
=> :seedling: Remove deprecated rate limit condition

Makefile, api/v1beta1/conditions_const.go, api/v1beta1/hetznerbaremetalmachine_types.go, docs/reference/hetzner-bare-metal-machine-template.md, hack/filter-caph-controller-manager-logs.py, hack/output-for-watch.sh, pkg/services/baremetal/client/ssh/download-from-oci.sh, pkg/services/baremetal/client/ssh/ssh_client.go, pkg/services/baremetal/host/host.go
Up to now, bare-metal machine images could only be downloaded from http/https URLs.
This PR make it possible to download the machine images from oci-registries.
You can use a tool like [oras](https://oras.land) to upload the machine image in tgz format to an oci registry.
=> :sparkles: download BM images via oci-registry.

templates/cluster-templates/bases/hcloud-kcp-fedora.yaml, templates/cluster-templates/bases/hcloud-kcp-packer.yaml, templates/cluster-templates/bases/hcloud-kcp-ubuntu.yaml, templates/cluster-templates/bases/hetznerbaremetal-kcp-ubuntu.yaml, templates/cluster-templates/cluster-class.yaml
The Kubernetes Controller Manager argument `pod-eviction-timeout` was deprecated with Kubernetes 1.26. Hence KCM won't come up successfully with clusters starting from version 1.27 when still passing this argument in cluster templates.
=> :bug: Remove deprecated KCM argument `pod-eviction-timeout`

Makefile, controllers/hetznerbaremetalhost_controller_test.go
This test was flaky. Increasing the timeout helped.
```
Summarizing 1 Failure:
[FAIL] HetznerBareMetalHostReconciler Tests with bm machine Test root device life cycle [It] reaches the state image installing
/home/guettli/syself/caph2/controllers/hetznerbaremetalhost_controller_test.go:347
Ran 95 of 95 Specs in 54.401 seconds
FAIL! -- 94 Passed | 1 Failed | 0 Pending | 0 Skipped
```
And decrease the timeout for tests. They take 2.5 min today. I decreased from 10min (default) to 5min, so that you don't want too long if they hang.
=> :seedling: fix flaky test, increase timeout.

test/e2e/config/hetzner-ci.yaml, test/e2e/config/hetzner.yaml
e2e upgrade test failed after waiting just one second.
This PR increases the wait time to 20 seconds.
Error was this:
> [FAILED] Timed out after 1.011s.
> 
> Deployment caph-system/caph-controller-manager failed to get status.Available = True condition
=> :seedling: increase wait time for e2e upgrade test.

api/v1beta1/groupversion_info.go, api/v1beta1/hcloudmachine_types.go, api/v1beta1/hcloudmachinetemplate_types.go, api/v1beta1/hcloudremediation_types.go, api/v1beta1/hcloudremediationtemplate_types.go, api/v1beta1/hetznerbaremetalhost_types.go, api/v1beta1/hetznerbaremetalmachine_types.go, api/v1beta1/hetznerbaremetalmachinetemplate_types.go, api/v1beta1/hetznerbaremetalremediation_types.go, api/v1beta1/hetznerbaremetalremediationtemplate_types.go, api/v1beta1/hetznercluster_types.go, api/v1beta1/hetznerclustertemplate_types.go
This commit uses apimachinery runtime package to create a new
schemeBuilder and then use that for registration of our types.
This removes adding types using controller-runtime scheme package.
Ref: https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.5-to-v1.6#suggested-changes-for-providers
Signed-off-by: Anurag <81210977+kranurag7@users.noreply.github.com>
=> ✨ change registration of types to scheme

controllers/hetznerbaremetalhost_controller.go, docs/developers/releasing.md
better error message if secret for BM is missing.
=> :seedling: better error message if secret for BM is missing.

api/v1beta1/conditions_const.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/state_machine.go
If downloading the image on a bare-metal server failed, it was up to now only visible in the logs.
This PR creates a status.condition.
=> :seedling: Create Condition if DownloadImage failed.

.lychee.toml, docs/reference/hetzner-bare-metal-machine-template.md, pkg/services/baremetal/client/ssh/ssh_client.go
Get BM machine image via oci token.
Before the PR $OCI_REGISTRY_AUTH_TOKEN needed to be "username:password"
How to test:
extract the shell script from the go code and use it to download an image.
for example: ghcr.io/syself/autopilot/node-images/staging/hetzner-apalla-1-27-workeramd64baremetal:v0-sha.2ae2207
=> :seedling: Get BM machine image via oci token

Makefile
If the .tiltbuild directory was absent, tilt would fail to run as it was trying to copy files to a non-existent directory.
Fixes #
**TODOs**:
=> 🐛 Create .tiltbuild directory in tilt-up

test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml
Two of the failing bare metal hosts used for testing has been fixed and this change is only to add them back.
Fixes #
**TODOs**:
=> :seedling: Add back fixed baremetal hosts

api/v1beta1/conditions_const.go, api/v1beta1/hetznercluster_types.go, api/v1beta1/hetznercluster_webhook.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go
This PR enables provisioning of Hetzner-based worker nodes using an externally managed Control Plane.
Fixes https://github.com/syself/cluster-api-provider-hetzner/issues/845
This PR is related to the PR https://github.com/syself/cluster-api-provider-hetzner/pull/848. With this code I was able to create a HetznerCluster with an external control plane and hetzner worker nodes.
**TODOs**:
=> :seedling: support externally managed control planes

pkg/services/hcloud/server/server.go
This PR aims to improve the removal of servers from the load balancer, avoiding downtime.
Fixes #1143
Unit tests will be created later.
**TODOs**:
=> 🐛 Remove server from load balancer after node is drained

pkg/services/hcloud/server/server.go
This PR fixes the issue of deleting servers introduced by [PR 1145](https://github.com/syself/cluster-api-provider-hetzner/pull/1145).
The server was being removed as a target from the load balancer during the load balancer reconciliation, and the server deletion function was trying to do that removal again and failing. Now there is a check, and only servers registered as targets are removed.
**TODOs**:
=> 🐛 Fix server deletion

pkg/services/hcloud/server/server.go
This PR aims to improve the addition of servers to the load balancer, avoiding downtime by adding them only after the API server pod is healthy.
Fixes #1148 
Unit tests will be added later.
**TODOs**:
=> :bug: Add servers to LB only after API server ready

docs/topics/node-image.md
Fixed structure, flow, and grammatical errors.
Fixes #
**TODOs**:
=> :book: Update node-image.md

docs/developers/development.md
Minor fixes
Fixes #
**TODOs**:
=> :book: Update development.md

docs/reference/hetzner-bare-metal-machine-template.md
Minor fixes 
Fixes #
**TODOs**:
=> :book: Update hetzner-bare-metal-machine-template.md with minor fixes

.github/workflows/pr-verify.yml, .github/workflows/schedule-link-checker.yml, .github/workflows/schedule-update-bot.yaml
- **migrate to create-github-app-token**
this commit migrates to officially maintained
way of generating token.
Signed-off-by: kranurag7 <anurag.kumar@syself.com>
=> :seedling: migrate to create-github-app-token

api/v1beta1/hetznerbaremetalhost_types.go
Added spec descriptions and some fixes.
Fixes #
**TODOs**:
=> 🌱 Update hetznerbaremetalhost_types.go

api/v1beta1/hetznerbaremetalhost_types.go, go.mod, go.sum, vendor/github.com/cloudflare/circl/ecc/goldilocks/twist.go, vendor/github.com/cloudflare/circl/internal/sha3/keccakf.go, vendor/github.com/cloudflare/circl/internal/sha3/sha3.go, vendor/github.com/cloudflare/circl/internal/sha3/shake.go, vendor/github.com/cloudflare/circl/math/primes.go, vendor/github.com/cloudflare/circl/sign/ed25519/ed25519.go, vendor/modules.txt
Ref: https://github.com/syself/cluster-api-provider-hetzner/security/dependabot/28
- **update dependencies to address security vuln**
we were using cloudflare/circl as indirect
dependency and dependabot alerted us about the
same. This commit updates the dependencies to the
latest version which has the fixes for the
security vulnerability.
Signed-off-by: kranurag7 <anurag.kumar@syself.com>
=> :seedling: update dependencies to address cloudflare/circl vuln

controllers/hetznerbaremetalhost_controller_test.go, go.mod, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/baremetal/baremetal_test.go
Skip machines with one WWN, if RAID is desired.
Fixes #1122 
**TODOs**:
=> :seedling: Skip machines with one WWN, if RAID is desired.

pkg/services/baremetal/host/utils.go, templates/cluster-templates/bases/hetznerbaremetal-mt-control-plane-ubuntu.yaml, templates/cluster-templates/bases/hetznerbaremetal-mt-md-1-ubuntu.yaml, templates/cluster-templates/cluster-class.yaml
This PR changes provisioning bare-metal machines. From now on we always create an UEFI boot partition.
This wastes 514MByte for systems without UEFI, but we think that should not matter much.
This should fix #1118 
on the ax41 (after the node is running). Check for uefi support:
```
root@... ~ # efibootmgr 
```
If you see that, then uefi is NOT running:
```
EFI variables are not supported on this system.
```
=> :seedling: Always create UEFI partition

test/e2e/Makefile
=> 🐛 fix ginkgo version mismatch

api/v1beta1/conditions_const.go, controllers/hetznerbaremetalhost_controller_test.go, hack/filter-caph-controller-manager-logs.py, pkg/services/baremetal/client/mocks/ssh/Client.go, pkg/services/baremetal/client/ssh/detect-linux-on-another-disk.sh, pkg/services/baremetal/client/ssh/ssh_client.go, pkg/services/baremetal/client/ssh/ssh_client_test.go, pkg/services/baremetal/host/host.go
If the WWN configuration of a hbmh is invalid, this PR detects that and creates a corresponding Event and Condition.
We think about doing that in Go with [go-diskfs](https://github.com/diskfs/go-diskfs)
Update: We will stick to the shell script. It works.
=> :bug: Script to detect invalid WWN/RAID configuration of hbmh.

api/v1beta1/hetznerbaremetalhost_types.go, api/v1beta1/hetznerbaremetalmachine_types.go, api/v1beta1/hetznerbaremetalmachine_types_test.go, controllers/hetznerbaremetalhost_controller.go, hack/filter-caph-controller-manager-logs.py, pkg/services/baremetal/client/ssh/detect-linux-on-another-disk.sh, pkg/services/baremetal/host/host.go, vendor/github.com/stretchr/testify/require/doc.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require.go.tmpl, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/require_forward.go.tmpl, vendor/github.com/stretchr/testify/require/requirements.go, vendor/modules.txt
Add Condition for missing rootDeviceHints of HetznerBareMetalHost
Better logging: Show URL of machine image (with password of URL redacted).
Update filter-caph-controller-manager-logs.py to cut very long output.
Adapt detect-linux-on-another-disk.sh to work on Ubuntu 20.04 and on machines with empty disks (no partitions yet).
Create events for InstallingMachineImageStarted to provide better hints about what is going on (and easier way to see how long these steps take).
=> :seedling: Several small changes to make debugging bare-metal provisioning easier

pkg/services/baremetal/client/ssh/ssh_client.go
If a bare-metal machine has several network interface cards, the provisioning did fail.
Fixes #939 
The PR makes the provisioning no longer fail.
BUT: Getting the INFO is broken in several ways:
* SPEED gets always fetched from eth0. It should be $iname instead.
* Getting the NIC via grepping lspci is not reliable. The name does not match to $iname.
Getting the NIC info in a more reliable way is a different PR.
**TODOs**:
=> :seedling: Fix getting NIC info if more than one card was found.

Tiltfile, api/v1beta1/hetznerbaremetalmachine_types_test.go, controllers/hetznerbaremetalhost_controller_test.go, pkg/services/baremetal/client/mocks/ssh/Client.go, pkg/services/baremetal/client/ssh/ssh_client.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go, pkg/services/hcloud/server/server_suite_test.go, templates/cluster-templates/bases/hcloud-kcp-fedora.yaml, templates/cluster-templates/bases/hcloud-kcp-ubuntu.yaml, templates/cluster-templates/bases/hetznerbaremetal-kcp-ubuntu.yaml, templates/cluster-templates/bases/hetznerbaremetal-mt-control-plane-ubuntu.yaml, templates/cluster-templates/bases/hetznerbaremetal-mt-md-1-ubuntu.yaml, templates/cluster-templates/bases/kct-md-0-fedora.yaml, templates/cluster-templates/bases/kct-md-0-ubuntu.yaml, templates/cluster-templates/cluster-class.yaml, templates/node-image/1.27.8-ubuntu-22-04-containerd/scripts/kubernetes.sh, templates/node-image/1.28.4-ubuntu-22-04-containerd/scripts/kubernetes.sh
The default templates of caph use Ubuntu 20.04.
This is old, and we have seen issues with new uefi-only machines, which could be related to that.
The PR changes some other things. `EOF` was changed to `EOF_VIA_SSH` because a nested heredoc which uses also EOF would fail.
And ~/.bashrc is not resolved. I use /root/.bashrc now.
=> :seedling: use ubuntu-22.04

pkg/services/baremetal/client/ssh/detect-linux-on-another-disk.sh
Up to now `detect-linux-on-another-disk.sh` did not detect /boot/efi partitions.
Now it detects such partitions.
This means install-image won't install if an efi-partition is on another disk, because this could make the reboot boot into another OS.
=> :seedling: detect efi partitions in detect-linux-on-another-disk.sh

pkg/services/baremetal/host/host.go
don't show "stderr" if there is no output.
up to now the event looked like this (via `k describe ...`), which looks very confusing. 
This PR does not emit "stderr:" if there is no stderr.
=> :seedling: improve event of GetHardwareDetailsDebug

.github/workflows/pr-lint.yml, docs/developers/development.md, docs/topics/preparation.md
when we mark a PR ready_for_review and if the changes are in docs directory then we are not checking for link failures and this was the reason why there was a commit on main which introduced link failures.
This commit fixes the same and introduces link checking even if we do some changes in the docs directory.
=> 🌱 fix links failures and enable link checking in docs directory

pkg/services/hcloud/remediation/remediation.go, pkg/services/hcloud/server/server.go
till now we only used numeric ID in logs which becomes sometimes hard during debugging as things needs to cross checked.
=> 🌱 log name of server and lb

api/v1beta1/hetznerbaremetalhost_types.go, controllers/hcloudmachine_controller.go, controllers/hetznerbaremetalhost_controller_test.go, controllers/hetznerbaremetalremediation_controller_test.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go
If a machine does not have root device hints, then the host gets chosen ignoring the config of the machinedeployment (RAID yes/no).
This is needed, so that the hmbh gets the rootDeviceHints populated.
Up to now this could lead to provisioning a machine for read, although not two WWNs were set.
Zulip [topic](https://chat.syself.org/#narrow/stream/20-project.2Fhetzner/topic/Check.20HBMH.20for.20WWN.20config)
=> :seedling: machinedeployment with RAID, reject host if not enough WWNs.

pkg/services/baremetal/host/host.go
Fix whitespace at end of `storage.vendor`
Fixes #1279 
**TODOs**:
=> 🌱Fix whitespace at end of storage vendor

api/v1beta1/hetznercluster_types.go, controllers/hetznerbaremetalhost_controller.go, controllers/hetznerbaremetalhost_controller_test.go, controllers/hetznerbaremetalmachine_controller_test.go, controllers/hetznerbaremetalremediation_controller_test.go, docs/topics/hetzner-baremetal.md, pkg/scope/baremetalhost.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_suite_test.go
Adding the feature to keep hostnames of bare metal servers constant. This can be triggered by a feature flag on the Cluster object. It takes the usual "bm-" prefix together with the cluster name as well as the serverID of the bare metal server.
This feature can be used by adding the annotation `"capi.syself.com/constant-bare-metal-hostname": "true"` to `Cluster` objects.
**TODOs**:
=> :sparkles: Add constant hostnames to bare metal servers

controllers/csr_controller.go
Better error message if CSR could not find machine.
From this log (converted from json to yaml), you don' know which machine was not found.
```
level: ERROR
time: "2024-05-02T12:41:30.204Z"
file: controllers/csr_controller.go:108
message: could not find an associated bm machine or hcloud machine
controller: certificatesigningrequest
controllerGroup: certificates.k8s.io
controllerKind: CertificateSigningRequest
"CertificateSigningRequest": {"name": "csr-7wttr"}
namespace: ""
name: csr-7wttr
reconcileID: 4f67ee9f-f920-4a32-8bac-36e7dfa38ee6
CertificateSigningRequest:
name: csr-7wttr
userName: system:node:guettli-1
error: failed to get hcloud and bare metal machine
stacktrace: |-
github.com/syself/cluster-api-provider-hetzner/controllers.(*GuestCSRRecon …
```
=> :seedling: Better error message if CSR could not find machine.

test/e2e/caph.go, test/e2e/common.go
We were running a script to redact the token in _artifacts directory which gets produced when we run our e2e tests. Since, ginkgo spec are run one after another, once first spec runs and we redact the logs, the manifest (kind: Secret) gets invalid and we get an error in our e2e tests.
`Error from server (BadRequest): error when creating "secret.yaml": Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 0`
This commit avoids redacting logs after each spec. We still do it after the whole suite completes.
=> 🌱 avoid redacting logs when running e2e tests

controllers/csr_controller.go, controllers/hetznercluster_controller.go
If a cluster uses ConstantBareMetalHostname, then the CSRs were not approved, since the node-name
did not match the expected pattern.
This PR extends the CSR approving, so that CSRs for constant bm hostnames get approved.
=> :bug: Fix CSR for ConstantBareMetalHostname

api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml, controllers/hetznercluster_controller.go
Adding the ssh key name via hetzner secret facilitates use cases where a lot of clusters are created with the same ssh key. Instead of having to specify it every time in the HetznerClusterTemplate object, it can be specified in the secret ones.
On top, this commit introduces default values for the HetznerSecret to allow use cases where all is hard-coded and doesn't have to be specified e.g. in a ClusterClass or in the templates of the cluster object anymore.
**TODOs**:
=> :sparkles: Add ssh key name via hetzner secret

api/v1beta1/hetznerbaremetalhost_types.go, api/v1beta1/hetznerbaremetalhost_types_test.go, hack/filter-caph-controller-manager-logs.py, pkg/services/baremetal/host/host.go
Provide better err msg if rescue system can't be reached. Handle this case better, because currently it reaches and endless loop of hardware reboots if a bare metal server's rescue system is not reachable.
Additionally, the controller emits an Event for every reboot now. This makes it more clear what is happening.
=> :seedling: handle case where rescue system can't be reached.

pkg/services/baremetal/client/ssh/detect-linux-on-another-disk.sh
Don't provision on devices containing a physical volume.
You can test it:
Enter rescue system on bm
```
mdadm --stop /dev/md0 
mdadm --stop /dev/md1 
wipefs -a ... 
pvcreate ...
```
Then runt the script `detect-linux-on-another-disk.sh` 
think about ways how this script could fail.
=> :seedling: Don't provision on devices containing a physical volume.

hack/ci-e2e-get-token.sh, pkg/services/baremetal/client/ssh/detect-linux-on-another-disk.sh
If there is an existing raid in a bare-metal server, and this old raid spans from root-devices to non-root-devices, then we don't want to use that machines.
It is likely that after executing installimage and restarting the server, that the old OS on the raid gets executed instead of the OS installed by installimage.
=> :seedling: Detect raid spanning root-device and non-root-device.

Makefile, Tiltfile, docs/developers/tilt.md, go.mod, go.sum, test/e2e/config/hetzner-ci.yaml, test/e2e/config/hetzner.yaml, vendor/modules.txt, vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster/cert_manager.go, vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/client/cluster/ownergraph.go, vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/client/config/cert_manager_client.go, vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/client/config/providers_client.go, vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/client/repository/components.go, vendor/sigs.k8s.io/cluster-api/test/e2e/cluster_upgrade_runtimesdk.go, vendor/sigs.k8s.io/cluster-api/test/framework/clusterctl/ca_injection.go, vendor/sigs.k8s.io/cluster-api/test/framework/clusterctl/clusterctl_helpers.go, vendor/sigs.k8s.io/cluster-api/test/framework/convenience.go, vendor/sigs.k8s.io/cluster-api/test/framework/finalizers_helpers.go, vendor/sigs.k8s.io/cluster-api/test/framework/ownerreference_helpers.go, vendor/sigs.k8s.io/cluster-api/test/framework/resourceversion_helpers.go
updates CAPI to 1.7.2
Fixes #
**TODOs**:
=> 🌱 update to CAPI 1.7.2

api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml
This PR changes the default of SSHKey from `ssh-key` to `hcloud-ssh-key-name` to make it more clear and avoid confusion.
=> 🌱 change SSHKey default name to hcloud-ssh-key-name

api/v1beta1/hcloudmachine_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, controllers/hetznercluster_controller.go, pkg/services/hcloud/server/server.go
In order to visualize which ssh keys have been used to provision a machine, we write the keys in the status of the HCloudMachine.
On top, we fix a bug where the "patch" call for the finalizer removed the ssh key from the spec of the HetznerCluster again, because it cannot patch the HetznerCluster.spec if a ClusterClass is used.
We add the ssh key now after the patch, so that it will still get patched at the end of the function, but can be used until then. In case of a ClusterClass we just don't have the key reflected in the spec of the HetznerCluster.
This is why we also add the list of keys to the HCloudMachine status, so that it is better visible.
**TODOs**:
=> :sparkles: Add ssh keys to status and fix ssh key in secret

controllers/hetznerbaremetalhost_controller.go, docs/topics/hetzner-baremetal.md, pkg/scope/baremetalhost.go
Allowing the annotation also on HetznerBaremetalMachine to achieve more flexibility (e.g. with regards to ClusterClass approaches).
**TODOs**:
=> :seedling: Allow constant hostname annotation on machines

api/v1beta1/hcloudmachine_types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachinetemplates.yaml
Adds the new server types `cx22`, `cx32`, `cx42` and `cx52` to the CRD validation. (There is no `cx12`). These were just launched and you can find out more at https://www.hetzner.com/news/new-cx-plans/
The previous generation (`cx11` - `cx51`) was deprecated and will be removed on 06 September 2024. I saw that you reference them in some templates and you might want to replace them until then.
Fixes #
**TODOs**:
=> :seedling: Add new CX server types

api/v1beta1/conditions_const.go, pkg/services/baremetal/host/host.go
Add condition indicating deletion timestamp is set
Fixes #1229
**TODOs**:
=> 🌱Add condition indicating deletion timestamp is set

controllers/hetznercluster_controller.go
Do not update hetznerCluster.Spec.SSHKeys.HCloud
This is not compatible with ClusterClass. CAPI would revert the change, and then there are two controllers switching the value on/off again and again.
=> :seedling: Do not update hetznerCluster.Spec.SSHKeys.HCloud

controllers/hetznerbaremetalhost_controller.go
Requeue after Deleting, and better log-message if HetznerCluster name is empty.
=> :seedling: Avoid misleading error logs when deleting hbmh

api/v1beta1/conditions_const.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go
Bare metal servers currently can time out while rebooting. However, the timeouts don't make too much sense right now.
- The timeout is too big, so that usually MachineHealthChecks will trigger before the timeout is reached. We reduce this here.
- The server was just rebooted again if a timeout is reached. However, if the timeout is actually reached, we don't want to continue, as there is probably something wrong with the server. Now we set a permanent error.
Additionally, there are some code improvements:
- The check whether a reboot has been triggered requires an API call to Hetzner API. This check is now only done when necessary, so that we safe the unneccessary API calls.
- We set a permanent error if a reboot is marked as failed, so that we stop …
=> :bug: Improve handling of bm server reboot timeouts

pkg/services/hcloud/machinetemplate/machinetemplate.go
We call the HCloud API in every reconcile loop of the hcloudmachine_template controller. This is not necessary since the server type does not change for one template object. We can set it once when the status is empty and then don't have to set it while the status is not nil anymore.
**TODOs**:
=> :seedling: Stop calling API when HCloudMachineTemplate status is set

controllers/csr_controller.go, test/e2e/log_collector.go
In this PR https://github.com/syself/cluster-api-provider-hetzner/pull/1351 we set the ProviderID earlier, but this did not work.
The linked PR was done to avoid error messages in the CSR-controller.
This PR changes the error messages of the CSR-controller. If the CSR exists, but there is no hbmm with the corresponding ProviderID, then this is fine. We wait some seconds and then we try again.
The hbmm is likely in state "ensure-provisioned", and the providerID will be set soon. INFO level logging is fine in this case.
=> :seedling: CSR uses INFO level if providerID was not set yet.

controllers/hcloudmachine_controller.go, controllers/hcloudmachine_controller_test.go, controllers/hetznercluster_controller.go, pkg/services/hcloud/server/server.go
- Filter HCloudMachine events so that status updates of the resource don't trigger another reconcilement of HCloudMachine
- Filter HetznerCluster events so that status updates of the resource don't trigger another reconcilement of HetznerCluster
- Filter HetznerCluster events so that some status updates that are not important don't trigger reconcilement of HCloudMachine
- Filter Machine events so that status updates of the resource don't trigger another reconcilement of HCloudMachine a
- Filter Cluster events so that status updates of the resource don't trigger another reconcilement of HetznerCluster
- Increase the time period to requeue if a server is starting
- Increase the time period to requeue if a server has not status yet
- Increase the time …
=> :seedling: Reduce reconcilements

controllers/hcloudmachine_controller_test.go, controllers/hetznercluster_controller_test.go
Add tests for #1359 
Fixes #1360
**TODOs**:
=> 🌱Add tests for reduce reconcilement predicate methods (PR 1359)

api/v1beta1/hcloudmachine_validation.go, api/v1beta1/hcloudmachine_validation_test.go, api/v1beta1/hcloudmachine_webhook.go, api/v1beta1/hcloudmachinetemplate_webhook.go, api/v1beta1/hetznerbaremetalmachine_validation.go, api/v1beta1/hetznerbaremetalmachine_validation_test.go, api/v1beta1/hetznerbaremetalmachine_webhook.go, api/v1beta1/hetznerbaremetalmachinetemplate_webhook.go, controllers/controllers_suite_test.go, controllers/hcloudmachine_controller_test.go, controllers/hcloudmachinetemplate_controller_test.go, controllers/hetznerbaremetalmachine_controller_test.go
=> 🌱Add checks in ValidCreate and ValidUpdate in hbmmt webhook

images/builder/Dockerfile, images/cache/Dockerfile, images/caph/Dockerfile
this was giving me warning locally and this commit fixes the same. Docker version used locally is 27.0.3
```bash
$ docker buildx build -f images/caph/Dockerfile . --check
[+] Building 0.9s (5/5) FINISHED                                                                                                                 docker:default
=> [internal] connecting to local controller                                                                                                              0.0s
=> [internal] load build definition from Dockerfile                                                                                                       0.0s
=> => transferring dockerfile: 1.57kB …
```
=> 🌱 change casing from as to AS in Dockerfile

pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/host_test.go
We have the timeout of one minute that we allow connection refused errors to come after reboot of a server.
In this commit we added the (correct) permanent error if we conclude the reboot to be "failed". However, apparently, for a long time already, we marked reboots as failed that did not actually fail.
This commit introduces a larger timeout, so that we don't mark the reboots as failed, and in turn don't mark the HetznerBareMetalHost as failed.
**TODOs**:
=> :bug: Increase timeout on connection refused errors

api/v1beta1/hetznerbaremetalmachinetemplate_webhook.go, controllers/hetznerbaremetalmachine_controller_test.go
We have to remove it as it is currently incapable of working with the ClusterClass.
**TODOs**:
=> :seedling: Remove HetznerBareMetalMachineTemplate create webhook

api/v1beta1/hcloudmachinetemplate_webhook.go, api/v1beta1/hetznerbaremetalmachinetemplate_webhook.go, controllers/hcloudmachinetemplate_controller_test.go, controllers/hetznerbaremetalmachine_controller_test.go
We introduced a bug previously by adding a duplicate validation in the
webhooks of HCloudMachineTemplate and HetznerBareMetalMachineTemplate in
the update function. There we used the function
ShouldSkipImmutabilityCheck that allows to use the webhook with Cluster
API's ClusterClass. However, we added another function call that again
checks that everything is immutable and didn't use the above utility
function from Cluster API. That's why the webhooks were not compatible
with ClusterClass anymore. All we have to do is to remove the duplicate
call that was not needed anyway.
**TODOs**:
=> :bug: Remove false duplicate validation in webhooks 

pkg/services/baremetal/host/host.go
In the provisioning of bare metal servers, we added permanent errors that appear after a server times out while rebooting.
This turned out to be quite unreliable, because the server reboots are very unreliable. Sometimes they take forever to reboot, in other situations they are fast and the server provisions successfully.
Therefore, we should rather try again and not stop completely.
**TODOs**:
=> :seedling: Remove permanent error after bm reboot

test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts-raid.yaml, test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml
The bm-2 (1716772)  seems broken. Rescue system is not reachable.
https://github.com/syself/cluster-api-provider-hetzner/actions/runs/10178928281/job/28153631149#step:3:825
And the hosts got renamed since "bm-2" does not say anything. If we use the robot-id in the name, then it is easier to find the related server.
=> :seedling: disable bm-2 (1716772) since broken. And rename hosts.

test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml
> Dear Client,
> We have replaced the defective SATA SSDs and started the server afterwards into the Linux rescue system
hardware was replaced. Rescue system works (tested by hand),
=> :seedling: re-enable bm server  bm-2 (1716772)

api/v1beta1/hetznercluster_webhook.go, api/v1beta1/types.go, config/crd/bases/infrastructure.cluster.x-k8s.io_hcloudmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclusters.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_hetznerclustertemplates.yaml
Add the new location `sin` (Singapore) and network zone `ap-southeast` to the CRDs + webhook validations.
The new location was released on 2024-08-06. Learn more at https://docs.hetzner.cloud/changelog#2024-08-06-new-location-singapore
Fixes #
**TODOs**:
=> :seedling: Add Singapore location and ap-southeast Network Zone

.lychee.toml, Makefile
LinkedIn return http status 999, which seem to confuse Lychee.
Related:
https://github.com/lycheeverse/lychee/issues/1477
=> :bug: Fix Lychee Link Checker

test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml
Fixing failing BM e2e test.
> missing storage device for root device hint "0x500a07510fe0ce34".
> Known WWNs: [0x5000cca22de4db5a 0x500a0751160cdc2d 0x5000cca22de4ef84 0x5002538d41d70a46]
=> e2e host has a new disk, adapting WWN

test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml
I sent a message to the support via the robot web-ui.
Example of a failing test: https://github.com/syself/cluster-api-provider-hetzner/actions/runs/10266506742/job/28406889169
=> :seedling: Disable "bm-e2e-1716772" since rescue system not reachable.

test/e2e/data/infrastructure-hetzner/v1beta1/bases/hetznerbaremetalhosts.yaml
enable bm-e2e-1716772 again. It was fixed by the Hetzner support.
=> :seedling: enable bm-e2e-1716772

Makefile
Example output (new):
```
lychee --verbose --config .lychee.toml ./*.md  ./docs/**/*.md 2>&1 | grep -vP '\[(200|EXCLUDED)\]'
? [999] https://www.linkedin.com/company/syself/ | Unknown status (999 <unknown status code>)
🔍 110 Total (in 6s) ✅ 96 OK 🚫 0 Errors 💤 13 Excluded
make: *** [Makefile:748: lint-links] Error 2
```
Now we would see the error, if this happens again.
=> :seedling: Make link checker lychee show  unknown http status codes

api/v1beta1/hetznerbaremetalhost_types.go, api/v1beta1/hetznerbaremetalhost_types_test.go, api/v1beta1/hetznerbaremetalremediation_types.go, controllers/csr_controller.go, controllers/hetznerbaremetalhost_controller.go, controllers/hetznerbaremetalhost_controller_test.go, pkg/services/baremetal/host/host.go
Fixes #1335
> There are multiple reasons why a HetznerBareMetalHost object has a "permanent error" set. This means that user intervention is required.
> The current work flow for users that have taken action on the server so that it can be used again to delete the custom resource and to recreate it. This is no issue at all from the workflow. However, it is not very elegant to delete an object and to manually re-create it.
=> :seedling: Set PermanentErrorAnnotation, if removed by user, then remove the error state.

test/e2e/caph.go
Then bm machines will get this name, and then it is easier to understand a failing e2e test.
It would be nice to see the ID here:
Unfortunately the JOB_ID is not available: https://github.com/actions/runner/issues/324
=> :seedling: Use GITHUB_RUN_ID for the specName of e2e tests.

pkg/services/hcloud/server/server.go
=> 🌱Add check to disallow hcloud servers without ssh key

controllers/csr_controller.go
If you saw this line in the logs, you thought that there is something wrong. We don't need to log that anymore. This part is stable.
=> :seedling: removed not needed log-line

api/v1beta1/hcloudmachine_types.go, api/v1beta1/hcloudremediation_types.go, api/v1beta1/hetznerbaremetalhost_types.go, api/v1beta1/hetznerbaremetalmachine_types.go, api/v1beta1/hetznerbaremetalremediation_types.go, api/v1beta1/hetznercluster_types.go, controllers/hcloudmachine_controller.go, controllers/hcloudmachinetemplate_controller.go, controllers/hcloudremediation_controller_test.go, controllers/hetznerbaremetalhost_controller.go, controllers/hetznerbaremetalhost_controller_test.go, controllers/hetznerbaremetalmachine_controller.go, controllers/hetznerbaremetalmachine_controller_test.go, controllers/hetznerbaremetalremediation_controller_test.go, controllers/hetznercluster_controller.go, pkg/secrets/secret.go, pkg/services/baremetal/host/host.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Update names of finalizers.
old: foo.infrastructure.cluster.x-k8s.io
new: infrastructure.cluster.x-k8s.io/foo
Related: https://github.com/syself/cluster-api-provider-hetzner/issues/1450
=> :seedling: Update names of finalizers.

pkg/services/hcloud/server/server.go, pkg/services/hcloud/server/server_test.go
=> 🌱Add handleRateLimit method

controllers/controllers_suite_test.go, controllers/hcloudmachine_controller_test.go, controllers/hcloudremediation_controller_test.go, controllers/hetznerbaremetalremediation_controller_test.go, controllers/hetznercluster_controller_test.go, pkg/services/hcloud/client/client.go, pkg/services/hcloud/client/fake/hcloud_client.go, pkg/services/hcloud/client/fake/hcloud_client_test.go, pkg/services/hcloud/client/mocks/Client.go, test/helpers/envtest.go
Avoid global hcloudClient. The hcloudClient got created once, and stored in a global variable. If the previous test left a fake hcloud-server in the client, then the next test sees a different result from hcloudClient.ListServers().
=> :seedling: fix flaky unit-tests

controllers/controllers_suite_test.go, controllers/hcloudmachine_controller_test.go, controllers/hcloudmachinetemplate_controller_test.go, controllers/hcloudremediation_controller_test.go, controllers/hetznercluster_controller_test.go, pkg/services/hcloud/client/client.go, pkg/services/hcloud/client/fake/hcloud_client.go, pkg/services/hcloud/client/fake/hcloud_client_test.go, pkg/services/hcloud/client/mocks/Client.go, test/helpers/envtest.go
After the firs "fix flaky tests" PR was merged, there were still flaky tests.
This PR moves the Reset into upper most BeforeEach and introduces the global variable again.
=> :seedling: Fix flaky tests 2

docs/caph/01-getting-started/02-quickstart/02-management-cluster-setup.md, docs/caph/01-getting-started/03-preparation.md, docs/caph/02-topics/05-baremetal/02-management-cluster.md
The make target `install-clusterctl` does not exist anymore.
=> :seedling: Fix typos in docs.

controllers/hetznercluster_controller.go, docs/caph/02-topics/06-advanced/01-csr-controller.md, main.go
This PR adds a flag that disables the `GuestCSRReconciler` for all workload clusters. This allows users to implement the CSR validation/approval logic themselves, making caph able to manage Kubernetes clusters that do not rely on Hetzner External/Internal IPs.
Fixes #1478
**TODOs**:
=> ✨Add flag to disable default CSR controller

config/manager/manager.yaml
This advice was found in the CAPI Upgrade Guide (1.7 to 1.8).
=> :seedling: set terminationMessagePolicy FallbackToLogsOnError.

.github/actions/e2e/action.yaml, README.md, docs/caph/01-getting-started/01-introduction.md, docs/caph/02-topics/04-upgrading-caph.md, docs/caph/02-topics/05-baremetal/02-management-cluster.md, docs/caph/03-reference/06-hetzner-bare-metal-machine-template.md
Update README to match CAPH v1.0.0
=> :seedling: Update README to match CAPH v1.0.0

README.md, controllers/hetznerbaremetalhost_controller.go, controllers/hetznercluster_controller.go, controllers/hetznercluster_controller_test.go, pkg/scope/cluster.go, pkg/services/baremetal/baremetal/baremetal.go, pkg/services/baremetal/host/host.go, pkg/services/baremetal/host/state_machine.go, pkg/services/hcloud/loadbalancer/loadbalancer.go, pkg/services/hcloud/network/network.go, pkg/services/hcloud/placementgroup/placementgroup.go, pkg/services/hcloud/server/server.go, pkg/services/hcloud/util/utils.go
**What this PR does / why we need it**: fix linting errors/warnings caused by the update of the linter `go-vet`
Fixes #
**TODOs**:
=> 🌱 fix linting

pkg/services/baremetal/client/ssh/check-disk.sh, pkg/services/baremetal/client/ssh/ssh_client.go
We found a strange issue with the check-disk.sh script. We add more output to the script, so that we can debug that better if it happens again. No fix, just more logging.
And the regex for valid WWNs was extended.
=> :seedling: More logging in check-disk.sh

templates/cluster-templates/bases/hcloud-kcp-ubuntu.yaml, templates/cluster-templates/bases/hetznerbaremetal-kcp-ubuntu.yaml, templates/cluster-templates/bases/kct-md-0-ubuntu.yaml, templates/node-image/1.28.9-ubuntu-22-04-containerd/scripts/cri.sh, templates/node-image/1.28.9-ubuntu-22-04-containerd/scripts/kubernetes.sh, templates/node-image/1.29.4-ubuntu-22-04-containerd/scripts/cri.sh, templates/node-image/1.29.4-ubuntu-22-04-containerd/scripts/kubernetes.sh
**What this PR does / why we need it**: Backwards compatible support for containerd 2
**Fixes**: https://github.com/syself/cluster-api-provider-hetzner/issues/1522
**Special notes for your reviewer**: I used a variation of this over the holidays while testing CAPH. The support for the 'batteries included' containerd release was deprecated a while ago and removed in containerd 2.0. This change updates the Ubuntu quickstart templates and packer templates to use the supported packaging for containerd and separately installs runc. This was tested with containerd 1.7.24 and containerd 2.0.1. 
One subtle change to make note of is moving the hardening of /etc/cni permissions into kubernetes.sh for the packer templates. Previously the containerd 'batteries included' package included …
=> ✨ Backwards compatible support for containerd 2

pkg/services/hcloud/client/fake/hcloud_client.go
`func (c *cacheHCloudClient) DeleteNetwork()`  did panic (on main).
[:seedling: Upgrade builder image to Go 1.23 (#1562) · syself/cluster-api-provider-hetzner@5b9c8aa](https://github.com/syself/cluster-api-provider-hetzner/actions/runs/13919667606/job/38949746367#step:7:1048)
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a7e422]
goroutine 492 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/home/runner/work/cluster-api-provider-hetzner/cluster-api-provider-hetzner/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:111 +0x1e5 …
```
=> :seedling: Fix nil pointer in hcloud fake client

Makefile, hack/kind-dev.sh
Hello! I wanted to run Tilt locally and noticed that it tries to download 1.35.6 image which is not exist here: https://github.com/fluxcd/flux-benchmark/pkgs/container/kindest%2Fnode/versions?filters%5Bversion_type%5D=tagged
and I noticed that there was a line deleted by accident in cillium install step.
=> :bug: Dev env bug fixes

pkg/services/baremetal/host/host.go
Conflict Errors should be visible as loglevel=info, so they are visible by default.
Otherwise, it is hard to understand why a second Reconcile happens again which seem to not see the changes made by the first Reconcile.
=> :seedling: Show conflicts in SaveHostAndReturn in logs

pkg/services/hcloud/server/server.go
We no longer get the error `load_balancer_not_found` if the target server was not found, instead we should check for the error `invalid_input`.
Fixes #1630 
**TODOs**:
=> :seedling: Look for different error code while deleting server of lb

go.mod, pkg/services/hcloud/server/server.go, pkg/services/hcloud/server/server_suite_test.go, pkg/services/hcloud/server/server_test.go
statusFromHCloudServer() overwrote the whole status of a hcloudmachine.
This was refactored to only update Status.Addresses.
Additionally, avoid modifying the input (`server.PublicNet.IPv6.IP`). The existing code already expected a wrong value ("2001:db8::2" instead of "2001:db8::1").
The test was converted to a plain Go test and avoids a global variable now.
Next PR: https://github.com/syself/cluster-api-provider-hetzner/pull/1650
=> :seedling: Refactor statusFromHCloudServer

test/e2e/e2e_suite_test.go
> I0829 08:31:00.251753   17515 request.go:697]
> Waited for 1.993332996s due to client-side
> throttling, not priority and fairness, request:
> GET:https://127.0.0.1:39499/apis/cluster.x-k8s.io/v1beta1/machines
This warning is repeated again and again in the output of e2e tests.
We use current api-servers, no need for client-side throttling.
Example output: https://github.com/syself/cluster-api-provider-hetzner/actions/runs/17318175493/job/49165317653#step:3:1661
=> :seedling: Avoid warning: Waited for due to client-side throttling,

metadata.yaml
Initializing a cluster using v1.0.6 with the following command fails with the included error.
```
clusterctl init --core cluster-api --bootstrap kubeadm --control-plane kubeadm --infrastructure hetzner
Fetching providers
Error: failed to fetch metadata for provider "infrastructure-hetzner" (version v1.0.6). Check that the release tag exists and the repository URL is correct — the project may have moved or the tag may be missing metadata.yaml: invalid provider metadata: unexpected kind "" for provider infrastructure-hetzner (expected "Metadata")
```
Adding the kind property with the value `Metadata` fixes the issue.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
=> 🐛 Update metadata.yaml to include kind property
